// Automatically generated by makemoduledefs.py.

extern const struct _mp_obj_module_t mp_module_array;
#undef MODULE_DEF_ARRAY
#define MODULE_DEF_ARRAY { MP_ROM_QSTR(MP_QSTR_array), MP_ROM_PTR(&mp_module_array) },

extern const struct _mp_obj_module_t mp_module_binascii;
#undef MODULE_DEF_BINASCII
#define MODULE_DEF_BINASCII { MP_ROM_QSTR(MP_QSTR_binascii), MP_ROM_PTR(&mp_module_binascii) },

extern const struct _mp_obj_module_t mp_module_collections;
#undef MODULE_DEF_COLLECTIONS
#define MODULE_DEF_COLLECTIONS { MP_ROM_QSTR(MP_QSTR_collections), MP_ROM_PTR(&mp_module_collections) },

extern const struct _mp_obj_module_t mp_module_errno;
#undef MODULE_DEF_ERRNO
#define MODULE_DEF_ERRNO { MP_ROM_QSTR(MP_QSTR_errno), MP_ROM_PTR(&mp_module_errno) },

extern const struct _mp_obj_module_t mp_module_io;
#undef MODULE_DEF_IO
#define MODULE_DEF_IO { MP_ROM_QSTR(MP_QSTR_io), MP_ROM_PTR(&mp_module_io) },

extern const struct _mp_obj_module_t mp_module_json;
#undef MODULE_DEF_JSON
#define MODULE_DEF_JSON { MP_ROM_QSTR(MP_QSTR_json), MP_ROM_PTR(&mp_module_json) },

extern const struct _mp_obj_module_t mp_module_re;
#undef MODULE_DEF_RE
#define MODULE_DEF_RE { MP_ROM_QSTR(MP_QSTR_re), MP_ROM_PTR(&mp_module_re) },

extern const struct _mp_obj_module_t mp_module_select;
#undef MODULE_DEF_SELECT
#define MODULE_DEF_SELECT { MP_ROM_QSTR(MP_QSTR_select), MP_ROM_PTR(&mp_module_select) },

extern const struct _mp_obj_module_t future_module;
#undef MODULE_DEF___FUTURE__
#define MODULE_DEF___FUTURE__ { MP_ROM_QSTR(MP_QSTR___future__), MP_ROM_PTR(&future_module) },

extern const struct _mp_obj_module_t mp_module___main__;
#undef MODULE_DEF___MAIN__
#define MODULE_DEF___MAIN__ { MP_ROM_QSTR(MP_QSTR___main__), MP_ROM_PTR(&mp_module___main__) },

extern const struct _mp_obj_module_t mp_module_asyncio;
#undef MODULE_DEF__ASYNCIO
#define MODULE_DEF__ASYNCIO { MP_ROM_QSTR(MP_QSTR__asyncio), MP_ROM_PTR(&mp_module_asyncio) },

extern const struct _mp_obj_module_t pixelmap_module;
#undef MODULE_DEF__PIXELMAP
#define MODULE_DEF__PIXELMAP { MP_ROM_QSTR(MP_QSTR__pixelmap), MP_ROM_PTR(&pixelmap_module) },

extern const struct _mp_obj_module_t adafruit_bus_device_module;
#undef MODULE_DEF_ADAFRUIT_BUS_DEVICE
#define MODULE_DEF_ADAFRUIT_BUS_DEVICE { MP_ROM_QSTR(MP_QSTR_adafruit_bus_device), MP_ROM_PTR(&adafruit_bus_device_module) },

extern const struct _mp_obj_module_t adafruit_bus_device_i2c_device_module;
#undef MODULE_DEF_ADAFRUIT_BUS_DEVICE_DOT_I2C_DEVICE
#define MODULE_DEF_ADAFRUIT_BUS_DEVICE_DOT_I2C_DEVICE { MP_ROM_QSTR(MP_QSTR_adafruit_bus_device_dot_i2c_device), MP_ROM_PTR(&adafruit_bus_device_i2c_device_module) },

extern const struct _mp_obj_module_t adafruit_bus_device_spi_device_module;
#undef MODULE_DEF_ADAFRUIT_BUS_DEVICE_DOT_SPI_DEVICE
#define MODULE_DEF_ADAFRUIT_BUS_DEVICE_DOT_SPI_DEVICE { MP_ROM_QSTR(MP_QSTR_adafruit_bus_device_dot_spi_device), MP_ROM_PTR(&adafruit_bus_device_spi_device_module) },

extern const struct _mp_obj_module_t pixelbuf_module;
#undef MODULE_DEF_ADAFRUIT_PIXELBUF
#define MODULE_DEF_ADAFRUIT_PIXELBUF { MP_ROM_QSTR(MP_QSTR_adafruit_pixelbuf), MP_ROM_PTR(&pixelbuf_module) },

extern const struct _mp_obj_module_t aesio_module;
#undef MODULE_DEF_AESIO
#define MODULE_DEF_AESIO { MP_ROM_QSTR(MP_QSTR_aesio), MP_ROM_PTR(&aesio_module) },

extern const struct _mp_obj_module_t analogbufio_module;
#undef MODULE_DEF_ANALOGBUFIO
#define MODULE_DEF_ANALOGBUFIO { MP_ROM_QSTR(MP_QSTR_analogbufio), MP_ROM_PTR(&analogbufio_module) },

extern const struct _mp_obj_module_t atexit_module;
#undef MODULE_DEF_ATEXIT
#define MODULE_DEF_ATEXIT { MP_ROM_QSTR(MP_QSTR_atexit), MP_ROM_PTR(&atexit_module) },

extern const struct _mp_obj_module_t bitbangio_module;
#undef MODULE_DEF_BITBANGIO
#define MODULE_DEF_BITBANGIO { MP_ROM_QSTR(MP_QSTR_bitbangio), MP_ROM_PTR(&bitbangio_module) },

extern const struct _mp_obj_module_t bitops_module;
#undef MODULE_DEF_BITOPS
#define MODULE_DEF_BITOPS { MP_ROM_QSTR(MP_QSTR_bitops), MP_ROM_PTR(&bitops_module) },

extern const struct _mp_obj_module_t board_module;
#undef MODULE_DEF_BOARD
#define MODULE_DEF_BOARD { MP_ROM_QSTR(MP_QSTR_board), MP_ROM_PTR(&board_module) },

extern const struct _mp_obj_module_t mp_module_builtins;
#undef MODULE_DEF_BUILTINS
#define MODULE_DEF_BUILTINS { MP_ROM_QSTR(MP_QSTR_builtins), MP_ROM_PTR(&mp_module_builtins) },

extern const struct _mp_obj_module_t busio_module;
#undef MODULE_DEF_BUSIO
#define MODULE_DEF_BUSIO { MP_ROM_QSTR(MP_QSTR_busio), MP_ROM_PTR(&busio_module) },

extern const struct _mp_obj_module_t codeop_module;
#undef MODULE_DEF_CODEOP
#define MODULE_DEF_CODEOP { MP_ROM_QSTR(MP_QSTR_codeop), MP_ROM_PTR(&codeop_module) },

extern const struct _mp_obj_module_t countio_module;
#undef MODULE_DEF_COUNTIO
#define MODULE_DEF_COUNTIO { MP_ROM_QSTR(MP_QSTR_countio), MP_ROM_PTR(&countio_module) },

extern const struct _mp_obj_module_t digitalio_module;
#undef MODULE_DEF_DIGITALIO
#define MODULE_DEF_DIGITALIO { MP_ROM_QSTR(MP_QSTR_digitalio), MP_ROM_PTR(&digitalio_module) },

extern const struct _mp_obj_module_t floppyio_module;
#undef MODULE_DEF_FLOPPYIO
#define MODULE_DEF_FLOPPYIO { MP_ROM_QSTR(MP_QSTR_floppyio), MP_ROM_PTR(&floppyio_module) },

extern const struct _mp_obj_module_t mp_module_gc;
#undef MODULE_DEF_GC
#define MODULE_DEF_GC { MP_ROM_QSTR(MP_QSTR_gc), MP_ROM_PTR(&mp_module_gc) },

extern const struct _mp_obj_module_t getpass_module;
#undef MODULE_DEF_GETPASS
#define MODULE_DEF_GETPASS { MP_ROM_QSTR(MP_QSTR_getpass), MP_ROM_PTR(&getpass_module) },

extern const struct _mp_obj_module_t hashlib_module;
#undef MODULE_DEF_HASHLIB
#define MODULE_DEF_HASHLIB { MP_ROM_QSTR(MP_QSTR_hashlib), MP_ROM_PTR(&hashlib_module) },

extern const struct _mp_obj_module_t i2ctarget_module;
#undef MODULE_DEF_I2CTARGET
#define MODULE_DEF_I2CTARGET { MP_ROM_QSTR(MP_QSTR_i2ctarget), MP_ROM_PTR(&i2ctarget_module) },

extern const struct _mp_obj_module_t imagecapture_module;
#undef MODULE_DEF_IMAGECAPTURE
#define MODULE_DEF_IMAGECAPTURE { MP_ROM_QSTR(MP_QSTR_imagecapture), MP_ROM_PTR(&imagecapture_module) },

extern const struct _mp_obj_module_t locale_module;
#undef MODULE_DEF_LOCALE
#define MODULE_DEF_LOCALE { MP_ROM_QSTR(MP_QSTR_locale), MP_ROM_PTR(&locale_module) },

extern const struct _mp_obj_module_t math_module;
#undef MODULE_DEF_MATH
#define MODULE_DEF_MATH { MP_ROM_QSTR(MP_QSTR_math), MP_ROM_PTR(&math_module) },

extern const struct _mp_obj_module_t memorymap_module;
#undef MODULE_DEF_MEMORYMAP
#define MODULE_DEF_MEMORYMAP { MP_ROM_QSTR(MP_QSTR_memorymap), MP_ROM_PTR(&memorymap_module) },

extern const struct _mp_obj_module_t microcontroller_module;
#undef MODULE_DEF_MICROCONTROLLER
#define MODULE_DEF_MICROCONTROLLER { MP_ROM_QSTR(MP_QSTR_microcontroller), MP_ROM_PTR(&microcontroller_module) },

extern const struct _mp_obj_module_t mp_module_micropython;
#undef MODULE_DEF_MICROPYTHON
#define MODULE_DEF_MICROPYTHON { MP_ROM_QSTR(MP_QSTR_micropython), MP_ROM_PTR(&mp_module_micropython) },

extern const struct _mp_obj_module_t msgpack_module;
#undef MODULE_DEF_MSGPACK
#define MODULE_DEF_MSGPACK { MP_ROM_QSTR(MP_QSTR_msgpack), MP_ROM_PTR(&msgpack_module) },

extern const struct _mp_obj_module_t nvm_module;
#undef MODULE_DEF_NVM
#define MODULE_DEF_NVM { MP_ROM_QSTR(MP_QSTR_nvm), MP_ROM_PTR(&nvm_module) },

extern const struct _mp_obj_module_t onewireio_module;
#undef MODULE_DEF_ONEWIREIO
#define MODULE_DEF_ONEWIREIO { MP_ROM_QSTR(MP_QSTR_onewireio), MP_ROM_PTR(&onewireio_module) },

extern const struct _mp_obj_module_t os_module;
#undef MODULE_DEF_OS
#define MODULE_DEF_OS { MP_ROM_QSTR(MP_QSTR_os), MP_ROM_PTR(&os_module) },

extern const struct _mp_obj_module_t pulseio_module;
#undef MODULE_DEF_PULSEIO
#define MODULE_DEF_PULSEIO { MP_ROM_QSTR(MP_QSTR_pulseio), MP_ROM_PTR(&pulseio_module) },

extern const struct _mp_obj_module_t pwmio_module;
#undef MODULE_DEF_PWMIO
#define MODULE_DEF_PWMIO { MP_ROM_QSTR(MP_QSTR_pwmio), MP_ROM_PTR(&pwmio_module) },

extern const struct _mp_obj_module_t qrio_module;
#undef MODULE_DEF_QRIO
#define MODULE_DEF_QRIO { MP_ROM_QSTR(MP_QSTR_qrio), MP_ROM_PTR(&qrio_module) },

extern const struct _mp_obj_module_t rainbowio_module;
#undef MODULE_DEF_RAINBOWIO
#define MODULE_DEF_RAINBOWIO { MP_ROM_QSTR(MP_QSTR_rainbowio), MP_ROM_PTR(&rainbowio_module) },

extern const struct _mp_obj_module_t random_module;
#undef MODULE_DEF_RANDOM
#define MODULE_DEF_RANDOM { MP_ROM_QSTR(MP_QSTR_random), MP_ROM_PTR(&random_module) },

extern const struct _mp_obj_module_t rp2pio_module;
#undef MODULE_DEF_RP2PIO
#define MODULE_DEF_RP2PIO { MP_ROM_QSTR(MP_QSTR_rp2pio), MP_ROM_PTR(&rp2pio_module) },

extern const struct _mp_obj_module_t storage_module;
#undef MODULE_DEF_STORAGE
#define MODULE_DEF_STORAGE { MP_ROM_QSTR(MP_QSTR_storage), MP_ROM_PTR(&storage_module) },

extern const struct _mp_obj_module_t struct_module;
#undef MODULE_DEF_STRUCT
#define MODULE_DEF_STRUCT { MP_ROM_QSTR(MP_QSTR_struct), MP_ROM_PTR(&struct_module) },

extern const struct _mp_obj_module_t supervisor_module;
#undef MODULE_DEF_SUPERVISOR
#define MODULE_DEF_SUPERVISOR { MP_ROM_QSTR(MP_QSTR_supervisor), MP_ROM_PTR(&supervisor_module) },

extern const struct _mp_obj_module_t mp_module_sys;
#undef MODULE_DEF_SYS
#define MODULE_DEF_SYS { MP_ROM_QSTR(MP_QSTR_sys), MP_ROM_PTR(&mp_module_sys) },

extern const struct _mp_obj_module_t time_module;
#undef MODULE_DEF_TIME
#define MODULE_DEF_TIME { MP_ROM_QSTR(MP_QSTR_time), MP_ROM_PTR(&time_module) },

extern const struct _mp_obj_module_t touchio_module;
#undef MODULE_DEF_TOUCHIO
#define MODULE_DEF_TOUCHIO { MP_ROM_QSTR(MP_QSTR_touchio), MP_ROM_PTR(&touchio_module) },

extern const struct _mp_obj_module_t traceback_module;
#undef MODULE_DEF_TRACEBACK
#define MODULE_DEF_TRACEBACK { MP_ROM_QSTR(MP_QSTR_traceback), MP_ROM_PTR(&traceback_module) },

extern const struct _mp_obj_module_t ulab_user_cmodule;
#undef MODULE_DEF_ULAB
#define MODULE_DEF_ULAB { MP_ROM_QSTR(MP_QSTR_ulab), MP_ROM_PTR(&ulab_user_cmodule) },

extern const struct _mp_obj_module_t ulab_numpy_module;
#undef MODULE_DEF_ULAB_DOT_NUMPY
#define MODULE_DEF_ULAB_DOT_NUMPY { MP_ROM_QSTR(MP_QSTR_ulab_dot_numpy), MP_ROM_PTR(&ulab_numpy_module) },

extern const struct _mp_obj_module_t ulab_fft_module;
#undef MODULE_DEF_ULAB_DOT_NUMPY_DOT_FFT
#define MODULE_DEF_ULAB_DOT_NUMPY_DOT_FFT { MP_ROM_QSTR(MP_QSTR_ulab_dot_numpy_dot_fft), MP_ROM_PTR(&ulab_fft_module) },

extern const struct _mp_obj_module_t ulab_linalg_module;
#undef MODULE_DEF_ULAB_DOT_NUMPY_DOT_LINALG
#define MODULE_DEF_ULAB_DOT_NUMPY_DOT_LINALG { MP_ROM_QSTR(MP_QSTR_ulab_dot_numpy_dot_linalg), MP_ROM_PTR(&ulab_linalg_module) },

extern const struct _mp_obj_module_t ulab_scipy_module;
#undef MODULE_DEF_ULAB_DOT_SCIPY
#define MODULE_DEF_ULAB_DOT_SCIPY { MP_ROM_QSTR(MP_QSTR_ulab_dot_scipy), MP_ROM_PTR(&ulab_scipy_module) },

extern const struct _mp_obj_module_t ulab_scipy_linalg_module;
#undef MODULE_DEF_ULAB_DOT_SCIPY_DOT_LINALG
#define MODULE_DEF_ULAB_DOT_SCIPY_DOT_LINALG { MP_ROM_QSTR(MP_QSTR_ulab_dot_scipy_dot_linalg), MP_ROM_PTR(&ulab_scipy_linalg_module) },

extern const struct _mp_obj_module_t ulab_scipy_optimize_module;
#undef MODULE_DEF_ULAB_DOT_SCIPY_DOT_OPTIMIZE
#define MODULE_DEF_ULAB_DOT_SCIPY_DOT_OPTIMIZE { MP_ROM_QSTR(MP_QSTR_ulab_dot_scipy_dot_optimize), MP_ROM_PTR(&ulab_scipy_optimize_module) },

extern const struct _mp_obj_module_t ulab_scipy_signal_module;
#undef MODULE_DEF_ULAB_DOT_SCIPY_DOT_SIGNAL
#define MODULE_DEF_ULAB_DOT_SCIPY_DOT_SIGNAL { MP_ROM_QSTR(MP_QSTR_ulab_dot_scipy_dot_signal), MP_ROM_PTR(&ulab_scipy_signal_module) },

extern const struct _mp_obj_module_t ulab_scipy_special_module;
#undef MODULE_DEF_ULAB_DOT_SCIPY_DOT_SPECIAL
#define MODULE_DEF_ULAB_DOT_SCIPY_DOT_SPECIAL { MP_ROM_QSTR(MP_QSTR_ulab_dot_scipy_dot_special), MP_ROM_PTR(&ulab_scipy_special_module) },

extern const struct _mp_obj_module_t ulab_utils_module;
#undef MODULE_DEF_ULAB_DOT_UTILS
#define MODULE_DEF_ULAB_DOT_UTILS { MP_ROM_QSTR(MP_QSTR_ulab_dot_utils), MP_ROM_PTR(&ulab_utils_module) },

extern const struct _mp_obj_module_t usb_module;
#undef MODULE_DEF_USB
#define MODULE_DEF_USB { MP_ROM_QSTR(MP_QSTR_usb), MP_ROM_PTR(&usb_module) },

extern const struct _mp_obj_module_t usb_cdc_module;
#undef MODULE_DEF_USB_CDC
#define MODULE_DEF_USB_CDC { MP_ROM_QSTR(MP_QSTR_usb_cdc), MP_ROM_PTR(&usb_cdc_module) },

extern const struct _mp_obj_module_t usb_core_module;
#undef MODULE_DEF_USB_DOT_CORE
#define MODULE_DEF_USB_DOT_CORE { MP_ROM_QSTR(MP_QSTR_usb_dot_core), MP_ROM_PTR(&usb_core_module) },

extern const struct _mp_obj_module_t usb_util_module;
#undef MODULE_DEF_USB_DOT_UTIL
#define MODULE_DEF_USB_DOT_UTIL { MP_ROM_QSTR(MP_QSTR_usb_dot_util), MP_ROM_PTR(&usb_util_module) },

extern const struct _mp_obj_module_t usb_host_module;
#undef MODULE_DEF_USB_HOST
#define MODULE_DEF_USB_HOST { MP_ROM_QSTR(MP_QSTR_usb_host), MP_ROM_PTR(&usb_host_module) },

extern const struct _mp_obj_module_t usb_video_module;
#undef MODULE_DEF_USB_VIDEO
#define MODULE_DEF_USB_VIDEO { MP_ROM_QSTR(MP_QSTR_usb_video), MP_ROM_PTR(&usb_video_module) },

extern const struct _mp_obj_module_t warnings_module;
#undef MODULE_DEF_WARNINGS
#define MODULE_DEF_WARNINGS { MP_ROM_QSTR(MP_QSTR_warnings), MP_ROM_PTR(&warnings_module) },

extern const struct _mp_obj_module_t watchdog_module;
#undef MODULE_DEF_WATCHDOG
#define MODULE_DEF_WATCHDOG { MP_ROM_QSTR(MP_QSTR_watchdog), MP_ROM_PTR(&watchdog_module) },

extern const struct _mp_obj_module_t zlib_module;
#undef MODULE_DEF_ZLIB
#define MODULE_DEF_ZLIB { MP_ROM_QSTR(MP_QSTR_zlib), MP_ROM_PTR(&zlib_module) },


#define MICROPY_REGISTERED_MODULES \
    MODULE_DEF_ADAFRUIT_BUS_DEVICE \
    MODULE_DEF_ADAFRUIT_BUS_DEVICE_DOT_I2C_DEVICE \
    MODULE_DEF_ADAFRUIT_BUS_DEVICE_DOT_SPI_DEVICE \
    MODULE_DEF_ADAFRUIT_PIXELBUF \
    MODULE_DEF_AESIO \
    MODULE_DEF_ANALOGBUFIO \
    MODULE_DEF_ATEXIT \
    MODULE_DEF_BITBANGIO \
    MODULE_DEF_BITOPS \
    MODULE_DEF_BOARD \
    MODULE_DEF_BUILTINS \
    MODULE_DEF_BUSIO \
    MODULE_DEF_CODEOP \
    MODULE_DEF_COUNTIO \
    MODULE_DEF_DIGITALIO \
    MODULE_DEF_FLOPPYIO \
    MODULE_DEF_GC \
    MODULE_DEF_GETPASS \
    MODULE_DEF_HASHLIB \
    MODULE_DEF_I2CTARGET \
    MODULE_DEF_IMAGECAPTURE \
    MODULE_DEF_LOCALE \
    MODULE_DEF_MATH \
    MODULE_DEF_MEMORYMAP \
    MODULE_DEF_MICROCONTROLLER \
    MODULE_DEF_MICROPYTHON \
    MODULE_DEF_MSGPACK \
    MODULE_DEF_NVM \
    MODULE_DEF_ONEWIREIO \
    MODULE_DEF_OS \
    MODULE_DEF_PULSEIO \
    MODULE_DEF_PWMIO \
    MODULE_DEF_QRIO \
    MODULE_DEF_RAINBOWIO \
    MODULE_DEF_RANDOM \
    MODULE_DEF_RP2PIO \
    MODULE_DEF_STORAGE \
    MODULE_DEF_STRUCT \
    MODULE_DEF_SUPERVISOR \
    MODULE_DEF_SYS \
    MODULE_DEF_TIME \
    MODULE_DEF_TOUCHIO \
    MODULE_DEF_TRACEBACK \
    MODULE_DEF_ULAB \
    MODULE_DEF_ULAB_DOT_NUMPY \
    MODULE_DEF_ULAB_DOT_NUMPY_DOT_FFT \
    MODULE_DEF_ULAB_DOT_NUMPY_DOT_LINALG \
    MODULE_DEF_ULAB_DOT_SCIPY \
    MODULE_DEF_ULAB_DOT_SCIPY_DOT_LINALG \
    MODULE_DEF_ULAB_DOT_SCIPY_DOT_OPTIMIZE \
    MODULE_DEF_ULAB_DOT_SCIPY_DOT_SIGNAL \
    MODULE_DEF_ULAB_DOT_SCIPY_DOT_SPECIAL \
    MODULE_DEF_ULAB_DOT_UTILS \
    MODULE_DEF_USB \
    MODULE_DEF_USB_CDC \
    MODULE_DEF_USB_DOT_CORE \
    MODULE_DEF_USB_DOT_UTIL \
    MODULE_DEF_USB_HOST \
    MODULE_DEF_USB_VIDEO \
    MODULE_DEF_WARNINGS \
    MODULE_DEF_WATCHDOG \
    MODULE_DEF_ZLIB \
    MODULE_DEF__ASYNCIO \
    MODULE_DEF__PIXELMAP \
    MODULE_DEF___FUTURE__ \
    MODULE_DEF___MAIN__ \
// MICROPY_REGISTERED_MODULES

#define MICROPY_REGISTERED_EXTENSIBLE_MODULES \
    MODULE_DEF_ARRAY \
    MODULE_DEF_BINASCII \
    MODULE_DEF_COLLECTIONS \
    MODULE_DEF_ERRNO \
    MODULE_DEF_IO \
    MODULE_DEF_JSON \
    MODULE_DEF_RE \
    MODULE_DEF_SELECT \
// MICROPY_REGISTERED_EXTENSIBLE_MODULES

extern void mp_module_sys_attr(mp_obj_t self_in, qstr attr, mp_obj_t *dest);
#define MICROPY_MODULE_DELEGATIONS \
    { MP_ROM_PTR(&mp_module_sys), mp_module_sys_attr }, \
// MICROPY_MODULE_DELEGATIONS
