// Automatically generated by make_root_pointers.py.

const char *cwd_path;
const char *readline_hist[(8)];
mp_obj_list_t mp_sys_argv_obj;
mp_obj_t background_pio_read[enum_NUM_DMA_CHANNELS];
mp_obj_t background_pio_write[enum_NUM_DMA_CHANNELS];
mp_obj_t counting[enum_NUM_PWM_SLICES];
mp_obj_t sys_mutable[MP_SYS_MUTABLE_NUM];
struct _mp_vfs_mount_t *vfs_cur;
struct _mp_vfs_mount_t *vfs_mount_table;
