// This file was automatically generated by maketranslatedata.py
#include "supervisor/shared/translate/compressed_string.h"

const struct compressed_string translation0 = { .data = 20, .tail = { 3, 243, 75, 24, 254, 92, 186, 127, 47, 72, 178, 41, 142, 85 } }; //   File \"%q\", line %d
const struct compressed_string translation1 = { .data = 16, .tail = { 9, 1, 181, 19, 198, 12, 114, 233, 231, 243, 0 } }; //  is of type %q\n
const struct compressed_string translation2 = { .data = 13, .tail = { 10, 210, 53, 108, 173, 124, 124, 254, 96 } }; //  not found.\n
const struct compressed_string translation3 = { .data = 10, .tail = { 13, 153, 198, 103, 238, 243, 249, 128 } }; //  output:\n
const struct compressed_string translation4 = { .data = 21, .tail = { 229, 202, 129, 76, 235, 1, 22, 67, 56, 166, 228, 224 } }; // %%c needs int or char
const struct compressed_string translation5 = { .data = 4, .tail = { 229, 245, 253, 191, 255, 128 } }; // %02X
const struct compressed_string translation6 = { .data = 2, .tail = { 229, 240 } }; // %S
const struct compressed_string translation7 = { .data = 2, .tail = { 229, 208 } }; // %q
const struct compressed_string translation8 = { .data = 32, .tail = { 229, 208, 18, 212, 114, 232, 40, 203, 36, 138, 43, 156, 89, 40, 82, 99, 8, 176 } }; // %q and %q contain duplicate pins
const struct compressed_string translation9 = { .data = 26, .tail = { 229, 208, 81, 150, 73, 22, 5, 115, 139, 37, 10, 76, 97, 22, 0 } }; // %q contains duplicate pins
const struct compressed_string translation10 = { .data = 35, .tail = { 229, 208, 34, 142, 93, 5, 243, 18, 52, 48, 218, 137, 227, 6, 57, 116, 244, 133, 105, 28, 186, 0 } }; // %q in %q must be of type %q, not %q
const struct compressed_string translation11 = { .data = 9, .tail = { 229, 208, 34, 140, 193, 128 } }; // %q in use
const struct compressed_string translation12 = { .data = 21, .tail = { 229, 208, 34, 212, 251, 134, 204, 134, 212, 57, 46, 198 } }; // %q index out of range
const struct compressed_string translation13 = { .data = 35, .tail = { 229, 208, 34, 213, 40, 112, 47, 152, 145, 161, 132, 89, 61, 141, 227, 210, 21, 164, 114, 128 } }; // %q indices must be integers, not %s
const struct compressed_string translation14 = { .data = 14, .tail = { 229, 208, 34, 164, 141, 73, 44, 117 } }; // %q init failed
const struct compressed_string translation15 = { .data = 20, .tail = { 229, 208, 88, 215, 105, 220, 95, 49, 35, 67, 28, 170 } }; // %q length must be %d
const struct compressed_string translation16 = { .data = 23, .tail = { 229, 208, 88, 215, 105, 220, 95, 49, 35, 67, 28, 171, 234, 229, 80 } }; // %q length must be %d-%d
const struct compressed_string translation17 = { .data = 23, .tail = { 229, 208, 88, 215, 105, 220, 95, 49, 35, 67, 31, 239, 247, 142, 85 } }; // %q length must be <= %d
const struct compressed_string translation18 = { .data = 23, .tail = { 229, 208, 88, 215, 105, 220, 95, 49, 35, 67, 31, 241, 247, 142, 85 } }; // %q length must be >= %d
const struct compressed_string translation19 = { .data = 13, .tail = { 229, 208, 95, 49, 35, 67, 28, 170 } }; // %q must be %d
const struct compressed_string translation20 = { .data = 16, .tail = { 229, 208, 95, 49, 35, 67, 28, 171, 234, 229, 80 } }; // %q must be %d-%d
const struct compressed_string translation21 = { .data = 16, .tail = { 229, 208, 95, 49, 35, 67, 31, 239, 247, 142, 85 } }; // %q must be <= %d
const struct compressed_string translation22 = { .data = 16, .tail = { 229, 208, 95, 49, 35, 67, 31, 241, 247, 142, 85 } }; // %q must be >= %d
const struct compressed_string translation23 = { .data = 50, .tail = { 229, 208, 95, 49, 35, 67, 4, 52, 226, 76, 157, 203, 128, 206, 9, 220, 184, 13, 168, 158, 48, 99, 159, 247, 230, 25, 199, 63, 199, 152 } }; // %q must be a bytearray or array of type 'H' or 'B'
const struct compressed_string translation24 = { .data = 27, .tail = { 229, 208, 95, 49, 35, 67, 4, 35, 58, 82, 197, 16, 27, 81, 203, 160 } }; // %q must be a subclass of %q
const struct compressed_string translation25 = { .data = 35, .tail = { 229, 208, 95, 49, 35, 67, 13, 168, 158, 48, 99, 151, 64, 206, 57, 116, 244, 133, 105, 28, 186, 0 } }; // %q must be of type %q or %q, not %q
const struct compressed_string translation26 = { .data = 29, .tail = { 229, 208, 95, 49, 35, 67, 13, 168, 158, 48, 99, 151, 79, 72, 86, 145, 203, 160 } }; // %q must be of type %q, not %q
const struct compressed_string translation27 = { .data = 15, .tail = { 229, 208, 54, 100, 54, 161, 201, 118, 48 } }; // %q out of range
const struct compressed_string translation28 = { .data = 22, .tail = { 229, 208, 68, 158, 5, 9, 85, 164, 104, 99, 232, 110, 192 } }; // %q step cannot be zero
const struct compressed_string translation29 = { .data = 11, .tail = { 229, 208, 75, 48, 179, 46, 192 } }; // %q too long
const struct compressed_string translation30 = { .data = 5, .tail = { 229, 211, 239, 229, 208 } }; // %q=%q
const struct compressed_string translation31 = { .data = 41, .tail = { 229, 211, 247, 229, 159, 224, 70, 233, 172, 192, 69, 23, 103, 49, 162, 76, 9, 220, 148, 97, 20, 81, 178, 178 } }; // %q[%u] shifts in more bits than pin count
const struct compressed_string translation32 = { .data = 42, .tail = { 229, 211, 247, 229, 159, 224, 70, 233, 172, 192, 108, 200, 187, 57, 141, 18, 96, 78, 228, 163, 8, 162, 141, 149, 144 } }; // %q[%u] shifts out more bits than pin count
const struct compressed_string translation33 = { .data = 21, .tail = { 229, 211, 247, 229, 159, 224, 102, 14, 1, 247, 151, 33, 132, 80 } }; // %q[%u] uses extra pin
const struct compressed_string translation34 = { .data = 38, .tail = { 229, 211, 247, 229, 159, 224, 118, 36, 152, 12, 161, 23, 25, 144, 217, 152, 74, 152, 109, 69, 27, 43, 32 } }; // %q[%u] waits on input outside of count
const struct compressed_string translation35 = { .data = 2, .tail = { 229, 0 } }; // %s
const struct compressed_string translation36 = { .data = 22, .tail = { 231, 203, 167, 48, 79, 182, 110, 107, 33, 207, 166, 81, 206, 160 } }; // '%q' argument required
const struct compressed_string translation37 = { .data = 33, .tail = { 231, 203, 167, 48, 218, 124, 206, 146, 42, 199, 1, 90, 68, 103, 24, 103, 145, 207, 151, 78, 96 } }; // '%q' object does not support '%q'
const struct compressed_string translation38 = { .data = 29, .tail = { 231, 203, 167, 48, 218, 124, 206, 146, 18, 23, 156, 130, 80, 146, 110, 82, 206 } }; // '%q' object isn't an iterator
const struct compressed_string translation39 = { .data = 26, .tail = { 231, 203, 167, 48, 218, 124, 206, 146, 18, 23, 156, 138, 21, 172, 90, 88, 192 } }; // '%q' object isn't callable
const struct compressed_string translation40 = { .data = 26, .tail = { 231, 203, 167, 48, 218, 124, 206, 146, 18, 23, 156, 132, 147, 114, 210, 198 } }; // '%q' object isn't iterable
const struct compressed_string translation41 = { .data = 43, .tail = { 231, 202, 57, 134, 211, 230, 116, 145, 86, 56, 94, 114, 35, 56, 195, 60, 132, 147, 184, 40, 132, 217, 110, 107, 32 } }; // '%s' object doesn't support item assignment
const struct compressed_string translation42 = { .data = 41, .tail = { 231, 202, 57, 134, 211, 230, 116, 145, 86, 56, 94, 114, 35, 56, 195, 60, 132, 147, 184, 169, 216, 229, 25, 64 } }; // '%s' object doesn't support item deletion
const struct compressed_string translation43 = { .data = 33, .tail = { 231, 202, 57, 134, 211, 230, 116, 145, 185, 64, 86, 5, 50, 233, 166, 100, 199, 62, 93, 57, 128 } }; // '%s' object has no attribute '%q'
const struct compressed_string translation44 = { .data = 31, .tail = { 231, 202, 57, 134, 211, 230, 116, 144, 144, 188, 228, 70, 116, 138, 58, 98, 75, 75, 24 } }; // '%s' object isn't subscriptable
const struct compressed_string translation45 = { .data = 52, .tail = { 231, 247, 243, 5, 100, 217, 110, 107, 33, 90, 65, 90, 205, 216, 234, 17, 68, 75, 162, 236, 53, 103, 185, 72, 140, 29, 19, 84, 55 } }; // '=' alignment not allowed in string format specifier
const struct compressed_string translation46 = { .data = 24, .tail = { 230, 93, 137, 39, 152, 108, 204, 37, 76, 107, 149, 164, 163, 40 } }; // 'await' outside function
const struct compressed_string translation47 = { .data = 31, .tail = { 231, 163, 153, 121, 115, 250, 185, 209, 150, 81, 114, 124, 195, 102, 97, 42, 98, 204, 216 } }; // 'break'/'continue' outside loop
const struct compressed_string translation48 = { .data = 25, .tail = { 230, 231, 57, 117, 230, 27, 51, 9, 83, 26, 229, 105, 40, 202 } }; // 'return' outside function
const struct compressed_string translation49 = { .data = 34, .tail = { 231, 194, 29, 170, 53, 118, 191, 48, 139, 9, 83, 5, 28, 45, 6, 185, 90, 74, 50, 128 } }; // 'yield from' inside async function
const struct compressed_string translation50 = { .data = 24, .tail = { 231, 194, 29, 171, 204, 54, 102, 18, 166, 53, 202, 210, 81, 148 } }; // 'yield' outside function
const struct compressed_string translation51 = { .data = 14, .tail = { 254, 96, 159, 96, 90, 201, 184, 254, 127, 204 } }; // * arg after **
const struct compressed_string translation52 = { .data = 28, .tail = { 254, 125, 197, 243, 18, 52, 48, 81, 9, 178, 220, 214, 68, 147, 236, 114 } }; // *x must be assignment target
const struct compressed_string translation53 = { .data = 9, .tail = { 244, 132, 81, 203, 167, 159, 204 } }; // , in %q\n
const struct compressed_string translation54 = { .data = 22, .tail = { 250, 252, 126, 177, 44, 8, 81, 175, 139, 31, 113, 134, 236, 110 } }; // 0.0 to a complex power
const struct compressed_string translation55 = { .data = 25, .tail = { 252, 43, 87, 56, 128, 228, 187, 24, 86, 144, 86, 179, 118, 58, 128 } }; // Address range not allowed
const struct compressed_string translation56 = { .data = 26, .tail = { 252, 43, 87, 56, 128, 228, 187, 24, 236, 229, 136, 4, 237, 149, 168 } }; // Address range wraps around
const struct compressed_string translation57 = { .data = 23, .tail = { 252, 45, 97, 91, 144, 166, 228, 170, 118, 128, 138, 51, 6 } }; // All dma channels in use
const struct compressed_string translation58 = { .data = 25, .tail = { 252, 45, 97, 18, 82, 98, 229, 77, 209, 78, 2, 40, 204, 24 } }; // All state machines in use
const struct compressed_string translation59 = { .data = 42, .tail = { 252, 20, 27, 187, 56, 106, 83, 46, 231, 81, 219, 116, 177, 135, 57, 116, 62, 168, 187, 14, 124, 163, 159, 221, 231, 243, 0 } }; // An error occurred while retrieving '%s':\n
const struct compressed_string translation60 = { .data = 39, .tail = { 252, 29, 203, 129, 124, 196, 138, 50, 201, 34, 141, 202, 218, 246, 103, 172, 15, 68, 241, 131, 28, 255, 191, 63, 0 } }; // Array must contain halfwords (type 'H')
const struct compressed_string translation61 = { .data = 36, .tail = { 252, 29, 203, 129, 212, 173, 147, 129, 27, 182, 109, 81, 161, 136, 69, 218, 198, 52, 226, 78, 60, 64 } }; // Array values should be single bytes.
const struct compressed_string translation62 = { .data = 21, .tail = { 252, 51, 45, 234, 115, 179, 21, 66, 64, 109, 117, 241, 243, 249, 128 } }; // Auto-reload is off.\n
const struct compressed_string translation63 = { .data = 85, .tail = { 252, 51, 45, 234, 115, 179, 21, 66, 64, 101, 241, 31, 4, 190, 45, 192, 130, 234, 99, 84, 177, 192, 110, 166, 227, 227, 240, 252, 68, 176, 124, 168, 157, 206, 225, 156, 26, 201, 184, 253, 127, 183, 191, 252, 9, 97, 84, 130, 210, 199, 227, 231, 243, 0 } }; // Auto-reload is on. Simply save files over USB to run them or enter REPL to disable.\n
const struct compressed_string translation64 = { .data = 41, .tail = { 252, 89, 164, 84, 250, 165, 12, 95, 49, 35, 67, 26, 163, 196, 143, 66, 44, 155, 234, 84, 49, 255, 175, 175, 195, 196 } }; // Boot device must be first (interface #0).
const struct compressed_string translation65 = { .data = 44, .tail = { 252, 115, 174, 166, 224, 236, 119, 53, 152, 23, 204, 72, 208, 199, 245, 26, 113, 39, 2, 204, 187, 6, 113, 99, 136 } }; // Buffer elements must be 4 bytes long or less
const struct compressed_string translation66 = { .data = 37, .tail = { 252, 115, 174, 166, 226, 249, 137, 26, 24, 33, 124, 218, 83, 22, 48, 218, 142, 85, 26, 113, 39, 0 } }; // Buffer must be a multiple of %d bytes
const struct compressed_string translation67 = { .data = 16, .tail = { 252, 115, 174, 166, 226, 89, 132, 92, 173, 96 } }; // Buffer too small
const struct compressed_string translation68 = { .data = 40, .tail = { 245, 254, 62, 177, 165, 154, 158, 80, 47, 152, 145, 161, 139, 230, 210, 152, 177, 192, 109, 71, 217, 254, 163, 78, 36, 224 } }; // CBC blocks must be multiples of 16 bytes
const struct compressed_string translation69 = { .data = 46, .tail = { 245, 251, 63, 95, 95, 199, 217, 251, 123, 255, 236, 85, 211, 169, 138, 54, 109, 80, 173, 35, 67, 26, 182, 86, 161, 156, 81, 204, 164, 235, 226 } }; // CIRCUITPY drive could not be found or created.
const struct compressed_string translation70 = { .data = 55, .tail = { 245, 149, 172, 35, 56, 55, 244, 120, 120, 252, 190, 72, 169, 63, 47, 151, 163, 192, 104, 122, 179, 152, 42, 80, 226, 17, 118, 10, 82, 157, 76, 54, 159, 51, 164, 248, 128 } }; // Call super().__init__() before accessing native object.
const struct compressed_string translation71 = { .data = 29, .tail = { 245, 146, 171, 72, 166, 228, 187, 24, 248, 252, 63, 17, 83, 234, 148, 56, 10, 221, 128 } }; // Cannot change USB devices now
const struct compressed_string translation72 = { .data = 20, .tail = { 245, 146, 171, 72, 169, 216, 228, 199, 82, 182, 78, 0 } }; // Cannot delete values
const struct compressed_string translation73 = { .data = 36, .tail = { 245, 146, 171, 72, 216, 228, 99, 54, 176, 237, 186, 88, 194, 40, 108, 206, 51, 34, 237, 83 } }; // Cannot get pull while in output mode
const struct compressed_string translation74 = { .data = 41, .tail = { 245, 146, 171, 72, 115, 187, 101, 100, 96, 167, 113, 219, 115, 81, 213, 33, 52, 177, 142, 168, 67, 227, 240, 252, 124, 64 } }; // Cannot remount path when visible via USB.
const struct compressed_string translation75 = { .data = 41, .tail = { 245, 146, 171, 72, 131, 145, 212, 173, 147, 29, 183, 53, 21, 71, 58, 74, 50, 132, 128, 139, 140, 207, 136 } }; // Cannot set value when direction is input.
const struct compressed_string translation76 = { .data = 21, .tail = { 245, 146, 171, 72, 140, 233, 75, 20, 64, 139, 37, 12 } }; // Cannot subclass slice
const struct compressed_string translation77 = { .data = 45, .tail = { 245, 146, 171, 72, 204, 24, 255, 159, 127, 179, 244, 250, 252, 124, 126, 207, 253, 137, 109, 142, 119, 55, 29, 146, 119, 31, 243, 239, 246, 126, 159, 211, 237, 241, 241, 254, 191, 252 } }; // Cannot use GPIO0..15 together with GPIO32..47
const struct compressed_string translation78 = { .data = 47, .tail = { 245, 163, 211, 41, 62, 254, 39, 118, 81, 70, 115, 20, 106, 152, 163, 148, 110, 117, 27, 147, 215, 196, 127, 157, 217, 177, 31, 233, 231, 243, 0 } }; // CircuitPython core code crashed hard. Whoops!\n
const struct compressed_string translation79 = { .data = 37, .tail = { 245, 182, 109, 80, 173, 32, 173, 102, 161, 73, 143, 203, 219, 248, 10, 22, 11, 75, 24, 211, 58, 234, 110 } }; // Could not allocate DMA capable buffer
const struct compressed_string translation80 = { .data = 4, .tail = { 252, 153, 76 } }; // Done
const struct compressed_string translation81 = { .data = 44, .tail = { 252, 157, 58, 152, 187, 84, 194, 180, 140, 193, 212, 118, 220, 212, 85, 28, 233, 40, 202, 18, 2, 46, 51, 62, 32 } }; // Drive mode not used when direction is input.
const struct compressed_string translation82 = { .data = 67, .tail = { 252, 178, 232, 187, 13, 201, 107, 100, 93, 131, 106, 39, 115, 5, 163, 117, 48, 125, 232, 120, 148, 101, 244, 130, 86, 157, 205, 193, 247, 161, 226, 81, 148, 53, 41, 151, 115, 175, 220 } }; // During handling of the above exception, another exception occurred:
const struct compressed_string translation83 = { .data = 39, .tail = { 254, 222, 191, 196, 50, 219, 128, 216, 55, 41, 56, 12, 163, 236, 255, 81, 167, 18, 112, 10, 65, 9, 75, 152 } }; // ECB only operates on 16 bytes at a time
const struct compressed_string translation84 = { .data = 14, .tail = { 254, 206, 236, 225, 20, 57, 236, 125, 192 } }; // Error in regex
const struct compressed_string translation85 = { .data = 21, .tail = { 254, 206, 236, 225, 20, 65, 106, 119, 106, 159, 142, 56, 241 } }; // Error in safemode.py.
const struct compressed_string translation86 = { .data = 32, .tail = { 252, 255, 63, 216, 36, 10, 158, 168, 167, 81, 171, 56, 90, 147, 185, 113, 1, 150, 220, 0 } }; // FFT is defined for ndarrays only
const struct compressed_string translation87 = { .data = 41, .tail = { 252, 255, 63, 216, 36, 4, 190, 44, 119, 53, 147, 168, 213, 156, 89, 20, 201, 193, 59, 151, 16, 25, 109, 192 } }; // FFT is implemented for linear arrays only
const struct compressed_string translation88 = { .data = 31, .tail = { 252, 201, 44, 117, 18, 195, 179, 164, 152, 69, 147, 117, 43, 13, 108, 81, 191, 136 } }; // Failed to write internal flash.
const struct compressed_string translation89 = { .data = 11, .tail = { 252, 210, 198, 15, 186, 68, 192 } }; // File exists
const struct compressed_string translation90 = { .data = 14, .tail = { 252, 210, 198, 21, 164, 106, 217, 90, 128 } }; // File not found
const struct compressed_string translation91 = { .data = 22, .tail = { 252, 242, 180, 148, 101, 14, 125, 50, 142, 112, 44, 212, 242 } }; // Function requires lock
const struct compressed_string translation92 = { .data = 47, .tail = { 254, 228, 245, 26, 150, 109, 63, 112, 185, 221, 159, 128, 84, 161, 196, 6, 112, 139, 18, 249, 164, 163, 40, 55, 118, 127, 16 } }; // Hard fault: memory access or instruction error.
const struct compressed_string translation93 = { .data = 36, .tail = { 254, 230, 88, 5, 107, 53, 10, 81, 148, 118, 220, 212, 127, 215, 180, 43, 72, 124, 170, 162, 237, 226 } }; // Heap allocation when VM not running.
const struct compressed_string translation94 = { .data = 28, .tail = { 246, 125, 95, 160, 108, 27, 148, 163, 40, 101, 20, 179, 65, 212, 106, 150, 48 } }; // I/O operation on closed file
const struct compressed_string translation95 = { .data = 21, .tail = { 246, 125, 190, 177, 131, 116, 198, 230, 229, 96, 138, 51, 6 } }; // I2C peripheral in use
const struct compressed_string translation96 = { .data = 42, .tail = { 246, 47, 171, 76, 235, 169, 184, 59, 29, 205, 102, 5, 243, 18, 52, 49, 254, 255, 120, 254, 163, 78, 36, 224, 89, 151, 96 } }; // In-buffer elements must be <= 4 bytes long
const struct compressed_string translation97 = { .data = 25, .tail = { 246, 42, 72, 195, 182, 206, 87, 16, 159, 67, 8, 189, 74, 201, 80 } }; // Init program size invalid
const struct compressed_string translation98 = { .data = 66, .tail = { 246, 42, 74, 21, 132, 28, 140, 34, 138, 163, 157, 37, 25, 69, 25, 117, 178, 82, 96, 118, 73, 220, 34, 164, 161, 88, 54, 100, 97, 20, 85, 28, 233, 40, 202 } }; // Initial set pin direction conflicts with initial out pin direction
const struct compressed_string translation99 = { .data = 58, .tail = { 246, 42, 74, 21, 132, 28, 140, 34, 136, 146, 147, 20, 101, 214, 201, 73, 129, 217, 39, 112, 138, 146, 133, 96, 217, 145, 132, 81, 18, 82, 96 } }; // Initial set pin state conflicts with initial out pin state
const struct compressed_string translation100 = { .data = 68, .tail = { 246, 46, 51, 35, 76, 235, 169, 184, 177, 174, 211, 184, 244, 114, 175, 128, 190, 98, 70, 134, 8, 95, 54, 148, 197, 140, 54, 162, 119, 49, 18, 228, 181, 20, 108, 172, 143, 71, 42, 248, 0 } }; // Input buffer length (%d) must be a multiple of the strand count (%d)
const struct compressed_string translation101 = { .data = 18, .tail = { 246, 46, 51, 63, 83, 102, 113, 153, 6, 238, 206 } }; // Input/output error
const struct compressed_string translation102 = { .data = 14, .tail = { 246, 44, 155, 169, 88, 27, 187, 56 } }; // Internal error
const struct compressed_string translation103 = { .data = 27, .tail = { 246, 44, 155, 169, 88, 57, 195, 101, 232, 126, 136, 240, 8, 163, 48, 96 } }; // Internal resource(s) in use
const struct compressed_string translation104 = { .data = 32, .tail = { 246, 44, 155, 169, 88, 118, 41, 166, 245, 109, 132, 165, 205, 193, 247, 194, 57, 215, 196 } }; // Internal watchdog timer expired.
const struct compressed_string translation105 = { .data = 16, .tail = { 246, 44, 155, 190, 113, 32, 221, 217, 252, 64 } }; // Interrupt error.
const struct compressed_string translation106 = { .data = 10, .tail = { 246, 47, 82, 178, 84, 114, 232 } }; // Invalid %q
const struct compressed_string translation107 = { .data = 14, .tail = { 246, 47, 82, 178, 84, 114, 232, 48, 138 } }; // Invalid %q pin
const struct compressed_string translation108 = { .data = 16, .tail = { 246, 47, 82, 178, 84, 19, 237, 155, 154, 200 } }; // Invalid argument
const struct compressed_string translation109 = { .data = 17, .tail = { 246, 47, 82, 178, 84, 105, 196, 152, 229, 227, 252, 224 } }; // Invalid byte %.*s
const struct compressed_string translation110 = { .data = 14, .tail = { 246, 47, 82, 178, 84, 106, 207, 114, 144 } }; // Invalid format
const struct compressed_string translation111 = { .data = 22, .tail = { 246, 47, 82, 178, 84, 101, 82, 141, 83, 7, 20, 44, 24 } }; // Invalid unicode escape
const struct compressed_string translation112 = { .data = 36, .tail = { 255, 233, 240, 47, 152, 145, 161, 143, 179, 253, 125, 35, 237, 254, 190, 144, 206, 63, 167, 218, 52, 226, 78, 5, 153, 118 } }; // Key must be 16, 24, or 32 bytes long
const struct compressed_string translation113 = { .data = 13, .tail = { 255, 233, 240, 21, 164, 106, 217, 90, 128 } }; // Key not found
const struct compressed_string translation114 = { .data = 32, .tail = { 255, 31, 223, 224, 27, 81, 228, 124, 118, 103, 168, 39, 216, 95, 49, 35, 67, 4, 161, 42 } }; // LHS of keyword arg must be an id
const struct compressed_string translation115 = { .data = 50, .tail = { 246, 165, 29, 189, 252, 78, 236, 163, 198, 248, 224, 106, 150, 63, 246, 25, 131, 30, 180, 122, 101, 39, 223, 196, 238, 202, 47, 142, 61, 84, 118, 136 } }; // MicroPython .mpy file; use CircuitPython mpy-cross
const struct compressed_string translation116 = { .data = 20, .tail = { 246, 164, 92, 166, 155, 157, 69, 74, 72, 66, 125, 12 } }; // Mismatched data size
const struct compressed_string translation117 = { .data = 20, .tail = { 246, 164, 92, 166, 155, 157, 68, 118, 44, 13, 108, 91, 0 } }; // Mismatched swap flag
const struct compressed_string translation118 = { .data = 41, .tail = { 246, 164, 66, 46, 195, 84, 120, 159, 146, 47, 203, 8, 190, 35, 151, 79, 223, 150, 127, 128, 230, 85, 129, 132, 95, 68, 120, 0 } }; // Missing first_in_pin. %q[%u] reads pin(s)
const struct compressed_string translation119 = { .data = 50, .tail = { 246, 164, 66, 46, 195, 84, 120, 159, 146, 47, 203, 8, 190, 35, 151, 79, 223, 150, 127, 129, 27, 166, 179, 1, 20, 106, 237, 113, 132, 95, 68, 120, 0 } }; // Missing first_in_pin. %q[%u] shifts in from pin(s)
const struct compressed_string translation120 = { .data = 47, .tail = { 246, 164, 66, 46, 195, 84, 120, 159, 146, 47, 203, 8, 190, 35, 151, 79, 223, 150, 127, 129, 216, 146, 96, 104, 80, 117, 12, 163, 8, 160 } }; // Missing first_in_pin. %q[%u] waits based on pin
const struct compressed_string translation121 = { .data = 50, .tail = { 246, 164, 66, 46, 195, 84, 120, 159, 147, 102, 126, 88, 69, 241, 28, 186, 126, 252, 179, 252, 8, 221, 53, 152, 13, 153, 18, 195, 8, 190, 136, 240 } }; // Missing first_out_pin. %q[%u] shifts out to pin(s)
const struct compressed_string translation122 = { .data = 43, .tail = { 246, 164, 66, 46, 195, 84, 120, 159, 147, 102, 126, 88, 69, 241, 28, 186, 126, 252, 179, 252, 14, 206, 146, 112, 48, 139, 232, 143, 0 } }; // Missing first_out_pin. %q[%u] writes pin(s)
const struct compressed_string translation123 = { .data = 41, .tail = { 246, 164, 66, 46, 195, 84, 120, 159, 148, 28, 252, 176, 139, 226, 57, 116, 253, 249, 103, 248, 16, 115, 3, 8, 190, 136, 240 } }; // Missing first_set_pin. %q[%u] sets pin(s)
const struct compressed_string translation124 = { .data = 36, .tail = { 246, 164, 66, 46, 195, 231, 124, 124, 176, 139, 226, 57, 116, 253, 249, 103, 248, 31, 60, 223, 16, 25, 70, 17, 64 } }; // Missing jmp_pin. %q[%u] jumps on pin
const struct compressed_string translation125 = { .data = 29, .tail = { 246, 182, 86, 70, 25, 22, 69, 81, 206, 146, 207, 192, 186, 68, 34, 236 } }; // Mount point directory missing
const struct compressed_string translation126 = { .data = 22, .tail = { 246, 230, 36, 104, 96, 135, 46, 130, 51, 165, 44, 81, 30, 32 } }; // Must be a %q subclass.
const struct compressed_string translation127 = { .data = 29, .tail = { 246, 230, 36, 97, 219, 170, 84, 199, 183, 217, 240, 253, 3, 56, 246, 254, 159, 15, 96, 194, 40 } }; // Must provide MISO or MOSI pin
const struct compressed_string translation128 = { .data = 42, .tail = { 247, 127, 143, 212, 124, 243, 124, 13, 73, 44, 117, 241, 31, 225, 60, 142, 220, 11, 157, 217, 248, 20, 103, 124, 226, 81, 151, 196 } }; // NLR jump failed. Likely memory corruption.
const struct compressed_string translation129 = { .data = 9, .tail = { 247, 48, 229, 208, 97, 20 } }; // No %q pin
const struct compressed_string translation130 = { .data = 30, .tail = { 247, 48, 246, 125, 190, 177, 83, 234, 148, 48, 82, 10, 181, 115, 136, 251, 135, 215, 223, 151, 112 } }; // No I2C device at address: 0x%x
const struct compressed_string translation131 = { .data = 20, .tail = { 247, 48, 163, 46, 169, 182, 92, 165, 25, 68, 28, 128 } }; // No configuration set
const struct compressed_string translation132 = { .data = 17, .tail = { 247, 48, 169, 234, 89, 180, 142, 93, 6, 153, 128 } }; // No default %q bus
const struct compressed_string translation133 = { .data = 28, .tail = { 247, 48, 220, 158, 189, 137, 204, 57, 45, 90, 224, 186, 146, 88, 180, 177, 128 } }; // No hardware random available
const struct compressed_string translation134 = { .data = 16, .tail = { 247, 48, 69, 8, 163, 14, 219, 57, 92 } }; // No in in program
const struct compressed_string translation135 = { .data = 23, .tail = { 247, 48, 69, 12, 225, 179, 33, 20, 97, 219, 103, 43, 128 } }; // No in or out in program
const struct compressed_string translation136 = { .data = 17, .tail = { 247, 48, 108, 200, 69, 24, 118, 217, 202, 224 } }; // No out in program
const struct compressed_string translation137 = { .data = 49, .tail = { 247, 48, 198, 109, 97, 156, 13, 91, 43, 80, 202, 62, 31, 151, 224, 25, 199, 195, 215, 254, 63, 216, 83, 115, 167, 144, 225, 178, 227, 178, 58, 46, 192 } }; // No pull up found on SDA or SCL; check your wiring
const struct compressed_string translation138 = { .data = 37, .tail = { 247, 48, 198, 109, 106, 183, 101, 12, 163, 8, 191, 236, 62, 207, 107, 111, 112, 231, 70, 189, 205, 106, 117 } }; // No pulldown on pin; 1Mohm recommended
const struct compressed_string translation139 = { .data = 35, .tail = { 247, 48, 198, 109, 108, 224, 50, 140, 34, 255, 176, 251, 61, 173, 189, 195, 157, 26, 247, 53, 169, 212 } }; // No pullup on pin; 1Mohm recommended
const struct compressed_string translation140 = { .data = 23, .tail = { 247, 48, 140, 21, 12, 88, 245, 144, 202, 42, 125, 82, 134 } }; // No space left on device
const struct compressed_string translation141 = { .data = 14, .tail = { 247, 48, 140, 211, 113, 83, 234, 148, 48 } }; // No such device
const struct compressed_string translation142 = { .data = 22, .tail = { 247, 48, 140, 211, 113, 170, 88, 254, 170, 163, 157, 37, 159, 128 } }; // No such file/directory
const struct compressed_string translation143 = { .data = 28, .tail = { 247, 48, 204, 104, 55, 104, 145, 134, 121, 8, 169, 40, 86, 79, 161, 212 } }; // No usb host port initialized
const struct compressed_string translation144 = { .data = 77, .tail = { 253, 52, 249, 157, 36, 110, 80, 52, 51, 81, 83, 69, 73, 66, 178, 125, 14, 160, 150, 162, 132, 161, 88, 89, 151, 99, 113, 161, 140, 193, 215, 196, 122, 220, 202, 76, 16, 83, 236, 27, 79, 153, 210, 124, 64 } }; // Object has been deinitialized and can no longer be used. Create a new object.
const struct compressed_string translation145 = { .data = 27, .tail = { 253, 22, 220, 6, 83, 5, 90, 185, 196, 4, 128, 86, 179, 118, 58, 128 } }; // Only one address is allowed
const struct compressed_string translation146 = { .data = 23, .tail = { 253, 48, 110, 82, 140, 161, 90, 70, 13, 238, 147, 39, 80 } }; // Operation not permitted
const struct compressed_string translation147 = { .data = 43, .tail = { 253, 51, 62, 173, 51, 174, 166, 224, 236, 119, 53, 152, 23, 204, 72, 208, 199, 251, 253, 227, 250, 141, 56, 147, 129, 102, 93, 128 } }; // Out-buffer elements must be <= 4 bytes long
const struct compressed_string translation148 = { .data = 24, .tail = { 247, 255, 159, 104, 139, 37, 12, 21, 156, 202, 188, 4, 81, 152, 48 } }; // PWM slice already in use
const struct compressed_string translation149 = { .data = 34, .tail = { 247, 255, 159, 104, 139, 37, 12, 83, 114, 85, 59, 15, 192, 21, 156, 202, 188, 4, 81, 152, 48 } }; // PWM slice channel A already in use
const struct compressed_string translation150 = { .data = 17, .tail = { 247, 155, 221, 34, 17, 148, 84, 213, 14, 160 } }; // Permission denied
const struct compressed_string translation151 = { .data = 19, .tail = { 247, 162, 138, 54, 86, 68, 179, 11, 19, 236, 96 } }; // Pin count too large
const struct compressed_string translation152 = { .data = 28, .tail = { 247, 162, 139, 230, 36, 104, 97, 148, 123, 255, 207, 180, 122, 247, 37, 83, 176, 252, 64 } }; // Pin must be on PWM Channel B
const struct compressed_string translation153 = { .data = 23, .tail = { 247, 162, 192, 190, 98, 70, 134, 32, 250, 100, 214, 80, 172 } }; // Pins must be sequential
const struct compressed_string translation154 = { .data = 10, .tail = { 247, 166, 12, 27, 187, 56 } }; // Pipe error
const struct compressed_string translation155 = { .data = 36, .tail = { 247, 219, 48, 9, 120, 23, 106, 230, 199, 1, 148, 78, 230, 53, 75, 28, 113, 18, 119, 243, 249, 128 } }; // Plus any modules on the filesystem\n
const struct compressed_string translation156 = { .data = 55, .tail = { 247, 183, 99, 113, 84, 198, 14, 190, 35, 218, 94, 70, 35, 46, 99, 134, 200, 39, 49, 135, 110, 169, 84, 93, 129, 171, 103, 109, 198, 27, 177, 191, 136 } }; // Power dipped. Make sure you are providing enough power.
const struct compressed_string translation157 = { .data = 56, .tail = { 247, 185, 196, 2, 94, 7, 145, 240, 37, 129, 172, 155, 137, 220, 199, 235, 253, 189, 255, 227, 196, 124, 96, 199, 175, 246, 253, 127, 199, 171, 242, 18, 193, 206, 204, 85, 241, 243, 249, 128 } }; // Press any key to enter the REPL. Use CTRL-D to reload.\n
const struct compressed_string translation158 = { .data = 35, .tail = { 247, 187, 108, 229, 113, 86, 56, 30, 207, 112, 236, 147, 187, 102, 69, 152, 170, 139, 176, 246, 124, 63, 80 } }; // Program does IN without loading ISR
const struct compressed_string translation159 = { .data = 36, .tail = { 247, 187, 108, 229, 113, 86, 56, 31, 167, 199, 246, 29, 146, 119, 108, 200, 179, 21, 81, 118, 31, 167, 195, 245 } }; // Program does OUT without loading OSR
const struct compressed_string translation160 = { .data = 20, .tail = { 247, 187, 108, 229, 113, 9, 244, 48, 139, 212, 172, 149 } }; // Program size invalid
const struct compressed_string translation161 = { .data = 39, .tail = { 247, 230, 214, 10, 210, 51, 7, 81, 219, 115, 81, 84, 115, 164, 163, 40, 72, 13, 153, 198, 103, 196 } }; // Pull not used when direction is output.
const struct compressed_string translation162 = { .data = 40, .tail = { 253, 125, 159, 15, 237, 242, 252, 61, 223, 151, 203, 243, 252, 63, 199, 248, 10, 210, 11, 169, 37, 139, 75, 24, 101, 19, 186, 64, 166, 233, 128 } }; // RISE_AND_FALL not available on this chip
const struct compressed_string translation163 = { .data = 34, .tail = { 253, 127, 111, 88, 72, 10, 210, 35, 56, 195, 60, 157, 67, 40, 157, 210, 6, 140, 79, 80 } }; // RTC is not supported on this board
const struct compressed_string translation164 = { .data = 9, .tail = { 253, 76, 171, 234, 101, 183, 0 } }; // Read-only
const struct compressed_string translation165 = { .data = 20, .tail = { 253, 76, 171, 234, 101, 183, 3, 84, 177, 199, 17, 39, 112 } }; // Read-only filesystem
const struct compressed_string translation166 = { .data = 33, .tail = { 253, 79, 166, 78, 36, 234, 63, 15, 237, 240, 23, 106, 152, 72, 25, 88, 206, 48, 207, 39, 80 } }; // Requested AES mode is unsupported
const struct compressed_string translation167 = { .data = 47, .tail = { 253, 114, 170, 139, 176, 69, 16, 90, 152, 187, 84, 255, 208, 123, 154, 67, 229, 85, 23, 97, 5, 212, 234, 40, 213, 63, 31, 63, 152 } }; // Running in safe mode! Not running saved code.\n
const struct compressed_string translation168 = { .data = 21, .tail = { 248, 123, 253, 131, 6, 233, 141, 205, 202, 193, 20, 102, 12 } }; // SPI peripheral in use
const struct compressed_string translation169 = { .data = 34, .tail = { 248, 89, 40, 96, 150, 163, 169, 91, 38, 42, 154, 234, 110, 107, 34, 198, 187, 78, 241, 226 } }; // Slice and value different lengths.
const struct compressed_string translation170 = { .data = 20, .tail = { 248, 89, 40, 112, 21, 164, 70, 113, 134, 121, 58, 128 } }; // Slices not supported
const struct compressed_string translation171 = { .data = 54, .tail = { 248, 54, 94, 134, 9, 106, 42, 113, 40, 165, 40, 202, 52, 206, 186, 155, 192, 190, 98, 70, 134, 39, 115, 16, 87, 49, 99, 93, 167, 112 } }; // Source and destination buffers must be the same length
const struct compressed_string translation172 = { .data = 36, .tail = { 248, 73, 83, 200, 55, 83, 125, 108, 221, 188, 71, 177, 104, 230, 80, 98, 36, 169, 228, 33, 62, 135, 226 } }; // Stack overflow. Increase stack size.
const struct compressed_string translation173 = { .data = 61, .tail = { 253, 183, 49, 255, 151, 74, 59, 81, 150, 93, 173, 99, 127, 252, 23, 106, 230, 198, 59, 20, 12, 193, 212, 75, 13, 25, 164, 34, 203, 8, 45, 76, 93, 170, 126, 32 } }; // The `microcontroller` module was used to boot into safe mode.
const struct compressed_string translation174 = { .data = 68, .tail = { 253, 183, 48, 90, 55, 83, 7, 222, 135, 137, 70, 81, 216, 160, 78, 230, 42, 142, 116, 145, 66, 204, 24, 109, 68, 238, 99, 86, 181, 155, 178, 46, 192, 251, 208, 241, 40, 203, 247, 0 } }; // The above exception was the direct cause of the following exception:
const struct compressed_string translation175 = { .data = 33, .tail = { 253, 183, 71, 175, 171, 4, 243, 192, 213, 30, 253, 137, 204, 106, 82, 86, 6, 238, 207, 226 } }; // Third-party firmware fatal error.
const struct compressed_string translation176 = { .data = 57, .tail = { 253, 183, 72, 23, 74, 59, 81, 150, 93, 173, 99, 113, 86, 56, 10, 210, 35, 56, 195, 60, 138, 50, 202, 46, 91, 48, 40, 88, 156, 185, 248, 128 } }; // This microcontroller does not support continuous capture.
const struct compressed_string translation177 = { .data = 36, .tail = { 253, 156, 168, 122, 21, 60, 135, 162, 237, 18, 28, 232, 107, 34, 133, 107, 11, 20, 79, 135, 221, 231, 243, 0 } }; // Traceback (most recent call last):\n
const struct compressed_string translation178 = { .data = 22, .tail = { 248, 254, 31, 175, 236, 48, 110, 152, 220, 220, 172, 17, 70, 96, 192 } }; // UART peripheral in use
const struct compressed_string translation179 = { .data = 4, .tail = { 248, 251, 63, 47, 184 } }; // UID:
const struct compressed_string translation180 = { .data = 51, .tail = { 248, 252, 63, 17, 83, 234, 148, 56, 10, 103, 81, 118, 115, 6, 181, 195, 34, 204, 9, 220, 148, 19, 152, 46, 164, 150, 45, 44, 126, 32 } }; // USB devices need more endpoints than are available.
const struct compressed_string translation181 = { .data = 45, .tail = { 248, 252, 63, 17, 83, 234, 148, 56, 17, 131, 162, 107, 192, 150, 97, 114, 94, 2, 44, 155, 234, 84, 48, 165, 115, 143, 16 } }; // USB devices specify too many interface names.
const struct compressed_string translation182 = { .data = 38, .tail = { 248, 169, 105, 99, 18, 192, 169, 67, 136, 25, 82, 178, 108, 167, 81, 236, 253, 3, 158, 201, 18, 110 } }; // Unable to access unaligned IO register
const struct compressed_string translation183 = { .data = 31, .tail = { 248, 169, 105, 99, 18, 192, 173, 102, 161, 73, 137, 97, 59, 152, 220, 203, 30, 32 } }; // Unable to allocate to the heap.
const struct compressed_string translation184 = { .data = 21, .tail = { 248, 169, 105, 99, 18, 193, 21, 36, 96, 158, 13, 192 } }; // Unable to init parser
const struct compressed_string translation185 = { .data = 23, .tail = { 248, 169, 105, 99, 18, 195, 179, 164, 152, 150, 11, 214, 254, 32 } }; // Unable to write to nvm.
const struct compressed_string translation186 = { .data = 35, .tail = { 248, 169, 105, 99, 18, 195, 179, 164, 152, 150, 14, 101, 95, 83, 45, 184, 23, 59, 179, 240 } }; // Unable to write to read-only memory
const struct compressed_string translation187 = { .data = 15, .tail = { 248, 175, 146, 183, 101, 14, 101, 12, 190, 32 } }; // Unknown reason.
const struct compressed_string translation188 = { .data = 55, .tail = { 248, 173, 202, 105, 185, 212, 46, 111, 161, 184, 109, 66, 73, 222, 3, 40, 253, 127, 191, 192, 122, 15, 190, 14, 146, 117, 28, 171, 233, 27, 52, 142, 85, 240, 241 } }; // Unmatched number of items on RHS (expected %d, got %d).
const struct compressed_string translation189 = { .data = 26, .tail = { 248, 172, 103, 24, 103, 147, 168, 220, 163, 112, 86, 217, 157, 39, 123, 128 } }; // Unsupported hash algorithm
const struct compressed_string translation190 = { .data = 48, .tail = { 255, 63, 135, 235, 238, 246, 123, 191, 231, 238, 31, 246, 217, 113, 70, 169, 141, 82, 198, 165, 115, 27, 148, 9, 236, 192, 251, 201, 172, 35, 44, 121, 252, 192 } }; // WARNING: Your code filename has two extensions\n
const struct compressed_string translation191 = { .data = 140, .tail = { 255, 39, 106, 53, 204, 75, 15, 194, 165, 171, 229, 36, 122, 209, 233, 148, 159, 127, 19, 187, 40, 229, 31, 233, 231, 243, 121, 252, 223, 244, 144, 146, 40, 143, 76, 164, 227, 137, 221, 151, 197, 159, 97, 171, 56, 187, 57, 132, 93, 89, 238, 82, 140, 190, 62, 127, 55, 159, 205, 251, 48, 178, 68, 141, 50, 150, 159, 82, 40, 187, 87, 54, 56, 19, 198, 12, 127, 230, 231, 108, 122, 63, 149, 218, 185, 177, 199, 242, 240, 255, 207, 31, 63, 152 } }; // Welcome to Adafruit CircuitPython %s!\n\nVisit circuitpython.org for more information.\n\nTo list built-in modules type `help(\"modules\")`.\n
const struct compressed_string translation192 = { .data = 39, .tail = { 255, 182, 200, 195, 156, 65, 212, 78, 230, 63, 31, 211, 244, 253, 134, 153, 153, 101, 5, 34, 36, 158, 70, 112 } }; // You pressed the BOOT button at start up
const struct compressed_string translation193 = { .data = 25, .tail = { 253, 229, 242, 180, 41, 58, 138, 228, 196, 176, 177, 174, 211, 191, 240 } }; // [truncated due to length]
const struct compressed_string translation194 = { .data = 22, .tail = { 243, 249, 189, 109, 83, 21, 101, 48, 249, 85, 69, 219, 199, 207, 230 } }; // \nCode done running.\n
const struct compressed_string translation195 = { .data = 48, .tail = { 243, 249, 189, 109, 83, 17, 45, 140, 29, 70, 156, 2, 204, 183, 169, 206, 204, 85, 241, 31, 169, 217, 138, 168, 187, 8, 102, 95, 31, 63, 152 } }; // \nCode stopped by auto-reload. Reloading soon.\n
const struct compressed_string translation196 = { .data = 85, .tail = { 243, 249, 189, 246, 50, 131, 26, 165, 140, 18, 132, 136, 201, 142, 201, 59, 142, 27, 46, 48, 237, 179, 149, 193, 72, 217, 39, 124, 233, 227, 70, 191, 212, 85, 45, 95, 41, 63, 85, 17, 233, 148, 156, 113, 59, 178, 253, 73, 17, 147, 143, 16 } }; // \nPlease file an issue with your program at github.com/adafruit/circuitpython/issues.
const struct compressed_string translation197 = { .data = 34, .tail = { 243, 249, 189, 238, 113, 1, 206, 14, 68, 176, 62, 233, 34, 11, 83, 23, 106, 159, 143, 159, 204 } }; // \nPress reset to exit safe mode.\n
const struct compressed_string translation198 = { .data = 33, .tail = { 243, 249, 191, 237, 178, 9, 204, 34, 136, 45, 76, 93, 170, 99, 67, 161, 102, 15, 238, 243, 249, 128 } }; // \nYou are in safe mode because:\n
const struct compressed_string translation199 = { .data = 39, .tail = { 249, 124, 145, 82, 126, 95, 47, 71, 128, 141, 219, 54, 168, 115, 156, 186, 143, 115, 41, 250, 66, 180, 142, 124, 163, 152 } }; // __init__() should return None, not '%s'
const struct compressed_string translation200 = { .data = 31, .tail = { 249, 124, 148, 251, 124, 190, 64, 159, 97, 124, 196, 141, 12, 16, 204, 27, 250, 167, 140, 24 } }; // __new__ arg must be a user-type
const struct compressed_string translation201 = { .data = 31, .tail = { 33, 167, 18, 113, 234, 178, 121, 24, 109, 62, 103, 73, 9, 1, 207, 166, 81, 206, 160 } }; // a bytes-like object is required
const struct compressed_string translation202 = { .data = 14, .tail = { 45, 25, 231, 209, 224, 40, 86, 177, 212 } }; // abort() called
const struct compressed_string translation203 = { .data = 18, .tail = { 42, 213, 206, 32, 224, 36, 3, 190, 39, 128 } }; // addresses is empty
const struct compressed_string translation204 = { .data = 29, .tail = { 39, 37, 216, 254, 225, 66, 85, 105, 20, 107, 227, 50, 98, 198, 187, 78, 224 } }; // arange: cannot compute length
const struct compressed_string translation205 = { .data = 24, .tail = { 39, 216, 36, 2, 80, 119, 196, 240, 32, 250, 100, 214, 134 } }; // arg is an empty sequence
const struct compressed_string translation206 = { .data = 35, .tail = { 39, 218, 25, 228, 19, 237, 155, 154, 200, 190, 98, 70, 134, 9, 66, 212, 157, 203, 128 } }; // argsort argument must be an ndarray
const struct compressed_string translation207 = { .data = 47, .tail = { 39, 218, 25, 228, 36, 5, 105, 9, 124, 88, 238, 107, 39, 81, 171, 56, 214, 197, 50, 106, 117, 4, 238, 92, 64 } }; // argsort is not implemented for flattened arrays
const struct compressed_string translation208 = { .data = 56, .tail = { 39, 219, 55, 53, 145, 124, 196, 141, 12, 123, 153, 79, 210, 9, 66, 44, 158, 198, 225, 156, 16, 156, 226, 198, 27, 80, 139, 39, 177, 188, 0 } }; // argument must be None, an integer or a tuple of integers
const struct compressed_string translation209 = { .data = 20, .tail = { 39, 219, 55, 53, 144, 165, 115, 14, 121, 131, 168 } }; // argument name reused
const struct compressed_string translation210 = { .data = 27, .tail = { 39, 219, 55, 53, 144, 185, 191, 213, 60, 96, 224, 93, 34, 229, 52, 220 } }; // argument num/types mismatch
const struct compressed_string translation211 = { .data = 26, .tail = { 39, 219, 55, 53, 152, 23, 204, 72, 208, 194, 212, 157, 203, 136 } }; // arguments must be ndarrays
const struct compressed_string translation212 = { .data = 36, .tail = { 39, 114, 224, 18, 212, 34, 212, 251, 139, 26, 237, 59, 139, 230, 36, 104, 96, 250, 100, 172 } }; // array and index length must be equal
const struct compressed_string translation213 = { .data = 16, .tail = { 39, 114, 224, 36, 9, 102, 26, 38, 192 } }; // array is too big
const struct compressed_string translation214 = { .data = 34, .tail = { 39, 114, 227, 234, 211, 137, 56, 14, 125, 50, 142, 117, 12, 161, 211, 109, 228, 66, 84, 192 } }; // array/bytes required on right side
const struct compressed_string translation215 = { .data = 37, .tail = { 40, 225, 104, 53, 103, 250, 187, 36, 238, 27, 51, 9, 83, 5, 28, 45, 6, 185, 90, 74, 50, 128 } }; // async for/with outside async function
const struct compressed_string translation216 = { .data = 50, .tail = { 41, 147, 190, 36, 75, 13, 142, 71, 160, 159, 111, 11, 162, 253, 94, 130, 125, 188, 46, 93, 195, 106, 14, 248, 158, 4, 31, 76, 154, 208, 192 } }; // attempt to get (arg)min/(arg)max of empty sequence
const struct compressed_string translation217 = { .data = 49, .tail = { 41, 147, 190, 36, 75, 13, 142, 65, 62, 215, 69, 250, 137, 246, 185, 119, 13, 168, 37, 7, 124, 79, 2, 15, 166, 77, 104, 96 } }; // attempt to get argmin/argmax of an empty sequence
const struct compressed_string translation218 = { .data = 24, .tail = { 41, 151, 77, 51, 39, 1, 90, 68, 103, 24, 103, 147, 168 } }; // attributes not supported
const struct compressed_string translation219 = { .data = 21, .tail = { 46, 233, 1, 32, 54, 100, 54, 163, 70, 202, 214, 0 } }; // axis is out of bounds
const struct compressed_string translation220 = { .data = 32, .tail = { 46, 233, 2, 249, 137, 26, 24, 247, 50, 159, 164, 51, 130, 80, 139, 39, 177, 184 } }; // axis must be None, or an integer
const struct compressed_string translation221 = { .data = 13, .tail = { 46, 233, 2, 89, 133, 153, 118 } }; // axis too long
const struct compressed_string translation222 = { .data = 16, .tail = { 208, 170, 40, 215, 194, 88, 197, 218, 166 } }; // bad compile mode
const struct compressed_string translation223 = { .data = 24, .tail = { 208, 170, 40, 203, 212, 222, 17, 148, 70, 14, 137, 170, 27, 128 } }; // bad conversion specifier
const struct compressed_string translation224 = { .data = 12, .tail = { 208, 170, 39, 140, 29, 26, 166 } }; // bad typecode
const struct compressed_string translation225 = { .data = 37, .tail = { 211, 58, 234, 110, 18, 4, 92, 173, 99, 113, 59, 146, 135, 62, 153, 56, 147, 168, 132, 250, 24 } }; // buffer is smaller than requested size
const struct compressed_string translation226 = { .data = 46, .tail = { 211, 58, 234, 110, 33, 62, 134, 47, 152, 145, 161, 130, 23, 205, 165, 49, 99, 13, 168, 59, 29, 205, 100, 66, 125, 12 } }; // buffer size must be a multiple of element size
const struct compressed_string translation227 = { .data = 29, .tail = { 211, 58, 234, 110, 33, 62, 134, 47, 152, 145, 114, 154, 110, 53, 103, 185, 72 } }; // buffer size must match format
const struct compressed_string translation228 = { .data = 37, .tail = { 211, 58, 234, 110, 34, 201, 67, 129, 124, 196, 141, 12, 54, 160, 250, 100, 172, 44, 107, 180, 238 } }; // buffer slices must be of equal length
const struct compressed_string translation229 = { .data = 16, .tail = { 211, 58, 234, 110, 37, 152, 69, 202, 214 } }; // buffer too small
const struct compressed_string translation230 = { .data = 17, .tail = { 211, 137, 58, 53, 76, 55, 83, 125, 108, 221, 128 } }; // bytecode overflow
const struct compressed_string translation231 = { .data = 40, .tail = { 211, 137, 56, 22, 53, 218, 119, 10, 210, 8, 95, 54, 148, 197, 140, 54, 161, 36, 238, 33, 62, 134 } }; // bytes length not a multiple of item size
const struct compressed_string translation232 = { .data = 24, .tail = { 211, 137, 56, 29, 74, 217, 48, 217, 144, 218, 135, 37, 216, 192 } }; // bytes value out of range
const struct compressed_string translation233 = { .data = 38, .tail = { 161, 40, 101, 183, 2, 48, 116, 77, 120, 12, 166, 50, 190, 74, 221, 148, 85, 46, 107, 8, 202 } }; // can only specify one unknown dimension
const struct compressed_string translation234 = { .data = 52, .tail = { 161, 47, 57, 5, 90, 136, 193, 209, 10, 194, 231, 59, 181, 68, 176, 43, 57, 149, 120, 245, 70, 116, 165, 138, 32, 234, 41, 98, 136 } }; // can't add special method to already-subclassed class
const struct compressed_string translation235 = { .data = 26, .tail = { 161, 47, 57, 5, 16, 155, 40, 150, 7, 223, 14, 113, 8, 202 } }; // can't assign to expression
const struct compressed_string translation236 = { .data = 17, .tail = { 161, 47, 57, 20, 37, 161, 216, 65, 219, 80 } }; // can't cancel self
const struct compressed_string translation237 = { .data = 22, .tail = { 161, 47, 57, 20, 101, 234, 111, 35, 151, 65, 44, 57, 116 } }; // can't convert %q to %q
const struct compressed_string translation238 = { .data = 27, .tail = { 161, 47, 57, 20, 101, 234, 111, 35, 148, 9, 97, 70, 190, 44, 125, 192 } }; // can't convert %s to complex
const struct compressed_string translation239 = { .data = 25, .tail = { 161, 47, 57, 20, 101, 234, 111, 35, 148, 9, 97, 173, 152, 164 } }; // can't convert %s to float
const struct compressed_string translation240 = { .data = 23, .tail = { 161, 47, 57, 20, 101, 234, 111, 35, 148, 9, 96, 139, 32 } }; // can't convert %s to int
const struct compressed_string translation241 = { .data = 42, .tail = { 161, 47, 57, 20, 101, 234, 111, 35, 159, 46, 156, 195, 105, 243, 58, 72, 150, 28, 186, 4, 190, 44, 148, 73, 183, 0 } }; // can't convert '%q' object to %q implicitly
const struct compressed_string translation242 = { .data = 27, .tail = { 161, 47, 57, 20, 115, 41, 49, 207, 151, 78, 97, 22, 36, 150, 135, 0 } }; // can't create '%q' instances
const struct compressed_string translation243 = { .data = 36, .tail = { 161, 47, 57, 21, 58, 88, 156, 194, 178, 217, 168, 86, 8, 161, 179, 38, 226, 141, 83 } }; // can't declare nonlocal in outer code
const struct compressed_string translation244 = { .data = 23, .tail = { 161, 47, 57, 21, 59, 28, 152, 62, 248, 115, 136, 70, 80 } }; // can't delete expression
const struct compressed_string translation245 = { .data = 20, .tail = { 161, 47, 57, 9, 124, 51, 200, 82, 185, 142, 93, 0 } }; // can't import name %q
const struct compressed_string translation246 = { .data = 29, .tail = { 161, 47, 57, 24, 55, 213, 158, 225, 206, 197, 41, 212, 194, 95, 12, 242 } }; // can't perform relative import
const struct compressed_string translation247 = { .data = 53, .tail = { 161, 47, 57, 16, 107, 80, 172, 190, 175, 115, 41, 142, 165, 108, 152, 150, 4, 62, 121, 137, 245, 68, 147, 201, 212, 108, 106, 110, 82, 206 } }; // can't send non-None value to a just-started generator
const struct compressed_string translation248 = { .data = 19, .tail = { 161, 47, 57, 16, 114, 10, 101, 211, 76, 201, 128 } }; // can't set attribute
const struct compressed_string translation249 = { .data = 24, .tail = { 161, 47, 57, 16, 114, 10, 101, 211, 76, 201, 142, 124, 186, 115 } }; // can't set attribute '%q'
const struct compressed_string translation250 = { .data = 73, .tail = { 161, 47, 57, 17, 217, 38, 155, 141, 93, 174, 11, 50, 215, 41, 74, 13, 80, 237, 80, 185, 190, 134, 232, 187, 9, 97, 114, 92, 149, 134, 168, 118, 168, 140, 29, 19, 84, 161, 74, 50, 128 } }; // can't switch from automatic field numbering to manual field specification
const struct compressed_string translation251 = { .data = 73, .tail = { 161, 47, 57, 17, 217, 38, 155, 141, 93, 174, 46, 75, 146, 176, 213, 14, 213, 17, 131, 162, 106, 148, 41, 70, 81, 44, 11, 50, 215, 41, 74, 13, 80, 237, 80, 185, 190, 134, 232, 187, 0 } }; // can't switch from manual field specification to automatic field numbering
const struct compressed_string translation252 = { .data = 38, .tail = { 161, 47, 57, 18, 249, 90, 20, 159, 170, 169, 213, 42, 96, 133, 26, 248, 177, 247, 11, 155, 232, 110 } }; // can't truncate-divide a complex number
const struct compressed_string translation253 = { .data = 10, .tail = { 161, 47, 57, 29, 137, 36 } }; // can't wait
const struct compressed_string translation254 = { .data = 23, .tail = { 161, 42, 180, 130, 136, 77, 148, 41, 246, 17, 185, 96, 192 } }; // cannot assign new shape
const struct compressed_string translation255 = { .data = 36, .tail = { 161, 42, 180, 138, 20, 72, 108, 206, 51, 35, 178, 78, 226, 133, 18, 139, 176, 124, 216, 192 } }; // cannot cast output with casting rule
const struct compressed_string translation256 = { .data = 28, .tail = { 161, 42, 180, 138, 157, 142, 76, 19, 185, 112, 14, 199, 115, 89, 128 } }; // cannot delete array elements
const struct compressed_string translation257 = { .data = 20, .tail = { 161, 42, 180, 135, 56, 220, 176, 96, 157, 203, 128 } }; // cannot reshape array
const struct compressed_string translation258 = { .data = 32, .tail = { 166, 239, 232, 240, 4, 251, 5, 105, 8, 161, 201, 118, 63, 71, 215, 223, 236, 251, 62, 191, 175, 235, 250, 252, 0 } }; // chr() arg not in range(0x110000)
const struct compressed_string translation259 = { .data = 24, .tail = { 163, 84, 195, 102, 97, 42, 97, 201, 118, 49, 245, 255, 251, 236, 251, 127, 248 } }; // code outside range 0~127
const struct compressed_string translation260 = { .data = 22, .tail = { 163, 95, 22, 62, 226, 169, 213, 42, 99, 78, 7, 208, 221, 128 } }; // complex divide by zero
const struct compressed_string translation261 = { .data = 40, .tail = { 163, 47, 86, 183, 83, 4, 251, 102, 230, 179, 2, 249, 137, 26, 24, 178, 41, 147, 130, 119, 46, 32 } }; // convolve arguments must be linear arrays
const struct compressed_string translation262 = { .data = 35, .tail = { 163, 47, 86, 183, 83, 4, 251, 102, 230, 179, 2, 249, 137, 26, 24, 90, 147, 185, 113, 0 } }; // convolve arguments must be ndarrays
const struct compressed_string translation263 = { .data = 36, .tail = { 163, 47, 86, 183, 83, 4, 251, 102, 230, 179, 2, 249, 137, 10, 210, 52, 48, 119, 196, 240 } }; // convolve arguments must not be empty
const struct compressed_string translation264 = { .data = 14, .tail = { 163, 59, 231, 18, 117, 26, 165, 140 } }; // corrupted file
const struct compressed_string translation265 = { .data = 35, .tail = { 163, 102, 213, 10, 210, 17, 122, 155, 200, 255, 162, 90, 155, 221, 150, 166, 46, 82, 233, 220 } }; // could not invert Vandermonde matrix
const struct compressed_string translation266 = { .data = 42, .tail = { 163, 180, 64, 72, 21, 61, 81, 78, 163, 86, 113, 246, 126, 64, 157, 203, 136, 13, 168, 177, 174, 211, 184, 254, 128 } }; // cross is defined for 1D arrays of length 3
const struct compressed_string translation267 = { .data = 24, .tail = { 169, 73, 9, 227, 6, 21, 164, 101, 106, 111, 18, 205, 80 } }; // data type not understood
const struct compressed_string translation268 = { .data = 29, .tail = { 169, 234, 89, 180, 142, 103, 222, 135, 137, 230, 47, 152, 145, 161, 139, 20, 72 } }; // default 'except' must be last
const struct compressed_string translation269 = { .data = 25, .tail = { 169, 234, 89, 180, 132, 128, 173, 32, 134, 185, 90, 74, 50, 128 } }; // default is not a function
const struct compressed_string translation270 = { .data = 37, .tail = { 170, 82, 70, 113, 82, 147, 16, 125, 50, 107, 67, 27, 148, 14, 206, 203, 176, 177, 174, 211, 184 } }; // dict update sequence has wrong length
const struct compressed_string translation271 = { .data = 32, .tail = { 170, 107, 168, 39, 219, 55, 53, 145, 124, 196, 141, 12, 18, 133, 169, 59, 151, 0 } }; // diff argument must be an ndarray
const struct compressed_string translation272 = { .data = 34, .tail = { 170, 107, 169, 185, 172, 161, 74, 50, 134, 122, 155, 134, 204, 134, 212, 57, 46, 198 } }; // differentiation order out of range
const struct compressed_string translation273 = { .data = 23, .tail = { 170, 92, 214, 17, 150, 5, 88, 43, 72, 185, 77, 55 } }; // dimensions do not match
const struct compressed_string translation274 = { .data = 14, .tail = { 170, 117, 74, 152, 211, 129, 244, 55, 96 } }; // divide by zero
const struct compressed_string translation275 = { .data = 16, .tail = { 170, 117, 72, 70, 81, 167, 3, 232, 110, 192 } }; // division by zero
const struct compressed_string translation276 = { .data = 31, .tail = { 172, 241, 131, 13, 168, 69, 159, 233, 246, 132, 128, 173, 34, 51, 140, 51, 201, 212 } }; // dtype of int32 is not supported
const struct compressed_string translation277 = { .data = 5, .tail = { 59, 226, 120 } }; // empty
const struct compressed_string translation278 = { .data = 10, .tail = { 59, 226, 120, 26, 165, 140 } }; // empty file
const struct compressed_string translation279 = { .data = 10, .tail = { 59, 226, 120, 27, 153, 96 } }; // empty heap
const struct compressed_string translation280 = { .data = 15, .tail = { 59, 226, 120, 16, 120, 39, 41, 103 } }; // empty separator
const struct compressed_string translation281 = { .data = 14, .tail = { 59, 226, 120, 16, 125, 50, 107, 67 } }; // empty sequence
const struct compressed_string translation282 = { .data = 5, .tail = { 53, 249, 124, 126, 0 } }; // en_US
const struct compressed_string translation283 = { .data = 41, .tail = { 62, 244, 60, 74, 50, 192, 190, 98, 69, 77, 211, 169, 141, 93, 174, 63, 18, 131, 254, 221, 232, 120, 148, 101 } }; // exceptions must derive from BaseException
const struct compressed_string translation284 = { .data = 35, .tail = { 62, 248, 58, 73, 212, 115, 251, 185, 130, 214, 77, 198, 172, 247, 41, 17, 131, 162, 106, 134, 224 } }; // expected ':' after format specifier
const struct compressed_string translation285 = { .data = 30, .tail = { 62, 248, 58, 74, 46, 195, 231, 152, 144, 67, 169, 91, 38, 53, 103, 16, 114 } }; // expecting just a value for set
const struct compressed_string translation286 = { .data = 28, .tail = { 62, 248, 58, 74, 46, 195, 200, 248, 251, 186, 149, 178, 99, 86, 113, 84, 164, 128 } }; // expecting key:value for dict
const struct compressed_string translation287 = { .data = 26, .tail = { 62, 243, 242, 221, 155, 200, 36, 5, 105, 4, 53, 202, 210, 81, 148 } }; // ext_hook is not a function
const struct compressed_string translation288 = { .data = 29, .tail = { 62, 242, 228, 60, 143, 142, 204, 245, 4, 251, 102, 230, 179, 3, 100, 234, 106 } }; // extra keyword arguments given
const struct compressed_string translation289 = { .data = 32, .tail = { 62, 242, 228, 48, 208, 146, 140, 165, 96, 79, 182, 110, 107, 48, 54, 78, 166, 160 } }; // extra positional arguments given
const struct compressed_string translation290 = { .data = 36, .tail = { 213, 44, 113, 196, 73, 220, 95, 49, 35, 14, 221, 82, 166, 46, 217, 89, 23, 57, 221, 170 } }; // filesystem must provide mount method
const struct compressed_string translation291 = { .data = 33, .tail = { 213, 30, 36, 19, 237, 155, 154, 200, 190, 98, 70, 134, 8, 80, 173, 98, 210, 198 } }; // first argument must be a callable
const struct compressed_string translation292 = { .data = 33, .tail = { 213, 30, 36, 19, 237, 155, 154, 200, 190, 98, 70, 134, 8, 107, 149, 164, 163, 40 } }; // first argument must be a function
const struct compressed_string translation293 = { .data = 42, .tail = { 213, 30, 36, 19, 237, 155, 154, 200, 190, 98, 70, 134, 8, 78, 113, 99, 13, 168, 90, 147, 185, 113, 0 } }; // first argument must be a tuple of ndarrays
const struct compressed_string translation294 = { .data = 33, .tail = { 213, 30, 36, 19, 237, 155, 154, 200, 190, 98, 70, 134, 9, 66, 212, 157, 203, 128 } }; // first argument must be an ndarray
const struct compressed_string translation295 = { .data = 38, .tail = { 213, 30, 36, 19, 237, 155, 154, 200, 150, 17, 156, 27, 250, 60, 5, 243, 18, 52, 49, 60, 96, 192 } }; // first argument to super() must be type
const struct compressed_string translation296 = { .data = 36, .tail = { 213, 30, 36, 79, 102, 4, 251, 102, 230, 179, 2, 249, 137, 26, 24, 90, 147, 185, 113, 0 } }; // first two arguments must be ndarrays
const struct compressed_string translation297 = { .data = 43, .tail = { 214, 197, 50, 106, 139, 176, 103, 169, 184, 190, 98, 70, 134, 13, 39, 115, 113, 207, 215, 207, 210, 25, 199, 63, 207, 152 } }; // flattening order must be either 'C', or 'F'
const struct compressed_string translation298 = { .data = 32, .tail = { 214, 201, 128, 79, 182, 110, 107, 34, 249, 137, 26, 24, 37, 11, 82, 119, 46, 0 } }; // flip argument must be an ndarray
const struct compressed_string translation299 = { .data = 19, .tail = { 213, 158, 229, 33, 76, 235, 0, 133, 82, 146 } }; // format needs a dict
const struct compressed_string translation300 = { .data = 42, .tail = { 213, 158, 229, 34, 37, 209, 118, 21, 74, 175, 57, 20, 101, 234, 111, 32, 173, 96, 79, 182, 110, 107, 48 } }; // format string didn't convert all arguments
const struct compressed_string translation301 = { .data = 34, .tail = { 213, 158, 229, 34, 37, 209, 118, 10, 103, 88, 23, 103, 48, 79, 182, 110, 107, 48 } }; // format string needs more arguments
const struct compressed_string translation302 = { .data = 4, .tail = { 215, 54, 176 } }; // full
const struct compressed_string translation303 = { .data = 39, .tail = { 215, 43, 73, 70, 81, 86, 56, 94, 114, 36, 188, 140, 121, 31, 29, 153, 234, 9, 246, 205, 205, 102, 0 } }; // function doesn't take keyword arguments
const struct compressed_string translation304 = { .data = 46, .tail = { 215, 43, 73, 70, 80, 125, 240, 116, 147, 168, 41, 23, 104, 145, 202, 160, 159, 108, 220, 214, 99, 210, 54, 105, 28, 170 } }; // function expected at most %d arguments, got %d
const struct compressed_string translation305 = { .data = 46, .tail = { 215, 43, 73, 70, 81, 179, 72, 190, 109, 41, 139, 24, 234, 86, 201, 192, 213, 156, 19, 237, 155, 154, 200, 231, 203, 167, 48 } }; // function got multiple values for argument '%q'
const struct compressed_string translation306 = { .data = 50, .tail = { 215, 43, 73, 70, 81, 185, 64, 157, 204, 65, 92, 196, 38, 202, 10, 68, 238, 96, 214, 176, 27, 80, 139, 38, 253, 74, 192 } }; // function has the same sign at the ends of interval
const struct compressed_string translation307 = { .data = 37, .tail = { 215, 43, 73, 70, 80, 144, 42, 122, 162, 157, 70, 172, 225, 106, 78, 229, 196, 6, 91, 112 } }; // function is defined for ndarrays only
const struct compressed_string translation308 = { .data = 49, .tail = { 215, 43, 73, 70, 81, 116, 136, 69, 216, 114, 168, 115, 233, 148, 115, 168, 195, 66, 74, 50, 149, 129, 62, 217, 185, 172, 192 } }; // function missing %d required positional arguments
const struct compressed_string translation309 = { .data = 38, .tail = { 215, 43, 73, 70, 81, 116, 136, 69, 216, 121, 31, 29, 153, 235, 234, 101, 183, 0, 159, 108, 220, 214, 64 } }; // function missing keyword-only argument
const struct compressed_string translation310 = { .data = 47, .tail = { 215, 43, 73, 70, 81, 116, 136, 69, 216, 57, 244, 202, 57, 212, 121, 31, 29, 153, 234, 9, 246, 205, 205, 100, 115, 229, 211, 152 } }; // function missing required keyword argument '%q'
const struct compressed_string translation311 = { .data = 49, .tail = { 215, 43, 73, 70, 81, 116, 136, 69, 216, 57, 244, 202, 57, 212, 97, 161, 37, 25, 74, 192, 159, 108, 220, 214, 71, 254, 185, 84 } }; // function missing required positional argument #%d
const struct compressed_string translation312 = { .data = 56, .tail = { 215, 43, 73, 70, 81, 37, 228, 112, 57, 84, 97, 161, 37, 25, 74, 192, 159, 108, 220, 214, 96, 105, 153, 28, 170, 59, 27, 152, 217, 58, 154, 128 } }; // function takes %d positional arguments but %d were given
const struct compressed_string translation313 = { .data = 27, .tail = { 216, 212, 220, 165, 156, 21, 156, 202, 188, 3, 238, 116, 204, 162, 236 } }; // generator already executing
const struct compressed_string translation314 = { .data = 31, .tail = { 216, 212, 220, 165, 156, 38, 202, 206, 117, 31, 242, 106, 110, 82, 207, 253, 187, 164, 128 } }; // generator ignored GeneratorExit
const struct compressed_string translation315 = { .data = 30, .tail = { 216, 212, 220, 165, 156, 57, 36, 29, 71, 194, 91, 30, 201, 55, 41, 70, 80 } }; // generator raised StopIteration
const struct compressed_string translation316 = { .data = 30, .tail = { 74, 154, 202, 106, 134, 225, 206, 167, 170, 41, 212, 20, 13, 172, 218, 21, 128 } }; // identifier redefined as global
const struct compressed_string translation317 = { .data = 32, .tail = { 74, 154, 202, 106, 134, 225, 206, 167, 170, 41, 212, 20, 5, 101, 179, 80, 172 } }; // identifier redefined as nonlocal
const struct compressed_string translation318 = { .data = 28, .tail = { 75, 225, 158, 71, 243, 10, 210, 10, 69, 218, 185, 177, 139, 31, 83, 176 } }; // import * not at module level
const struct compressed_string translation319 = { .data = 22, .tail = { 69, 163, 95, 5, 41, 165, 140, 120, 223, 28, 2, 122, 110 } }; // incompatible .mpy arch
const struct compressed_string translation320 = { .data = 22, .tail = { 69, 163, 95, 5, 41, 165, 140, 120, 223, 28, 13, 82, 198 } }; // incompatible .mpy file
const struct compressed_string translation321 = { .data = 17, .tail = { 69, 163, 95, 22, 57, 49, 171, 61, 202, 64 } }; // incomplete format
const struct compressed_string translation322 = { .data = 21, .tail = { 69, 163, 95, 22, 57, 49, 171, 61, 202, 71, 145, 240 } }; // incomplete format key
const struct compressed_string translation323 = { .data = 17, .tail = { 69, 163, 59, 157, 36, 96, 171, 84, 93, 128 } }; // incorrect padding
const struct compressed_string translation324 = { .data = 22, .tail = { 69, 169, 247, 9, 1, 179, 33, 181, 26, 54, 86, 176 } }; // index is out of bounds
const struct compressed_string translation325 = { .data = 26, .tail = { 69, 169, 247, 23, 204, 72, 208, 196, 231, 22, 48, 206, 17, 100 } }; // index must be tuple or int
const struct compressed_string translation326 = { .data = 18, .tail = { 69, 169, 247, 13, 153, 13, 168, 114, 93, 140 } }; // index out of range
const struct compressed_string translation327 = { .data = 50, .tail = { 69, 170, 80, 224, 95, 49, 35, 67, 8, 178, 123, 27, 199, 164, 69, 146, 135, 30, 144, 206, 63, 22, 107, 25, 40, 178, 68, 192 } }; // indices must be integers, slices, or Boolean lists
const struct compressed_string translation328 = { .data = 34, .tail = { 69, 198, 100, 18, 212, 54, 103, 25, 145, 84, 185, 172, 35, 44, 10, 166, 186, 155, 128 } }; // input and output dimensions differ
const struct compressed_string translation329 = { .data = 30, .tail = { 69, 198, 100, 18, 212, 54, 103, 25, 145, 27, 150, 14, 5, 83, 93, 77, 192 } }; // input and output shapes differ
const struct compressed_string translation330 = { .data = 53, .tail = { 69, 198, 100, 19, 237, 155, 154, 200, 190, 98, 70, 134, 9, 66, 44, 158, 198, 254, 144, 66, 115, 139, 31, 164, 51, 130, 22, 72, 144 } }; // input argument must be an integer, a tuple, or a list
const struct compressed_string translation331 = { .data = 37, .tail = { 69, 198, 100, 19, 185, 112, 44, 107, 180, 238, 47, 152, 145, 161, 140, 55, 99, 112, 218, 143, 180 } }; // input array length must be power of 2
const struct compressed_string translation332 = { .data = 31, .tail = { 69, 198, 100, 19, 185, 113, 0, 156, 194, 180, 138, 53, 240, 82, 154, 88, 192 } }; // input arrays are not compatible
const struct compressed_string translation333 = { .data = 30, .tail = { 69, 198, 100, 84, 164, 133, 243, 18, 52, 48, 74, 18, 77, 203, 75, 24 } }; // input data must be an iterable
const struct compressed_string translation334 = { .data = 21, .tail = { 69, 198, 100, 36, 5, 105, 9, 38, 229, 165, 140 } }; // input is not iterable
const struct compressed_string translation335 = { .data = 26, .tail = { 69, 198, 100, 92, 165, 211, 184, 72, 5, 28, 94, 231, 46, 148 } }; // input matrix is asymmetric
const struct compressed_string translation336 = { .data = 24, .tail = { 69, 198, 100, 92, 165, 211, 184, 72, 16, 139, 182, 108, 78 } }; // input matrix is singular
const struct compressed_string translation337 = { .data = 29, .tail = { 69, 198, 100, 95, 49, 35, 67, 4, 42, 107, 6, 22, 164, 238, 92, 0 } }; // input must be a dense ndarray
const struct compressed_string translation338 = { .data = 29, .tail = { 69, 198, 100, 95, 49, 35, 67, 12, 167, 234, 170, 92, 214, 17, 148, 172 } }; // input must be one-dimensional
const struct compressed_string translation339 = { .data = 27, .tail = { 69, 198, 100, 95, 49, 35, 67, 17, 211, 36, 230, 46, 82, 233, 220 } }; // input must be square matrix
const struct compressed_string translation340 = { .data = 44, .tail = { 69, 198, 100, 95, 49, 35, 67, 19, 156, 88, 253, 34, 201, 19, 233, 14, 75, 177, 250, 67, 56, 90, 147, 185, 112 } }; // input must be tuple, list, range, or ndarray
const struct compressed_string translation341 = { .data = 37, .tail = { 69, 198, 100, 117, 58, 75, 60, 11, 230, 36, 104, 97, 181, 7, 211, 37, 97, 99, 93, 167, 112 } }; // input vectors must be of equal length
const struct compressed_string translation342 = { .data = 50, .tail = { 69, 147, 124, 4, 129, 83, 213, 20, 234, 53, 103, 31, 103, 228, 18, 77, 203, 75, 28, 6, 212, 31, 76, 149, 133, 141, 118, 157, 192 } }; // interp is defined for 1D iterables of equal length
const struct compressed_string translation343 = { .data = 17, .tail = { 69, 234, 86, 74, 131, 239, 67, 196, 163, 40 } }; // invalid exception
const struct compressed_string translation344 = { .data = 24, .tail = { 69, 234, 86, 74, 141, 89, 238, 82, 35, 7, 68, 213, 13, 192 } }; // invalid format specifier
const struct compressed_string translation345 = { .data = 29, .tail = { 69, 234, 86, 74, 139, 165, 29, 177, 196, 238, 202, 42, 116, 103, 41, 103 } }; // invalid micropython decorator
const struct compressed_string translation346 = { .data = 12, .tail = { 69, 234, 86, 74, 136, 147, 192 } }; // invalid step
const struct compressed_string translation347 = { .data = 14, .tail = { 69, 234, 86, 74, 136, 225, 100, 187, 128 } }; // invalid syntax
const struct compressed_string translation348 = { .data = 39, .tail = { 69, 234, 86, 74, 136, 225, 100, 187, 141, 89, 194, 44, 158, 198, 227, 178, 78, 227, 66, 131, 28, 170 } }; // invalid syntax for integer with base %d
const struct compressed_string translation349 = { .data = 25, .tail = { 69, 234, 86, 74, 136, 225, 100, 187, 141, 89, 194, 230, 250, 27, 128 } }; // invalid syntax for number
const struct compressed_string translation350 = { .data = 34, .tail = { 72, 140, 233, 75, 20, 71, 163, 192, 19, 236, 62, 193, 124, 196, 141, 12, 16, 165, 138, 32 } }; // issubclass() arg 1 must be a class
const struct compressed_string translation351 = { .data = 56, .tail = { 72, 140, 233, 75, 20, 71, 163, 192, 19, 236, 62, 209, 124, 196, 141, 12, 16, 165, 138, 32, 51, 130, 19, 156, 88, 195, 106, 41, 98, 136, 56 } }; // issubclass() arg 2 must be a class or a tuple of classes
const struct compressed_string translation352 = { .data = 27, .tail = { 73, 55, 41, 70, 88, 21, 74, 133, 105, 20, 101, 234, 111, 177, 128 } }; // iterations did not converge
const struct compressed_string translation353 = { .data = 68, .tail = { 249, 178, 40, 62, 248, 58, 76, 2, 22, 72, 144, 218, 136, 151, 250, 180, 226, 78, 3, 105, 243, 58, 76, 10, 50, 194, 68, 154, 200, 236, 147, 184, 131, 182, 161, 180, 249, 157, 36 } }; // join expects a list of str/bytes objects consistent with self object
const struct compressed_string translation354 = { .data = 61, .tail = { 242, 62, 59, 51, 212, 19, 237, 155, 154, 207, 162, 60, 2, 180, 132, 190, 44, 119, 53, 147, 168, 245, 12, 193, 133, 103, 185, 88, 19, 237, 1, 22, 36, 202, 160 } }; // keyword argument(s) not implemented - use normal args instead
const struct compressed_string translation355 = { .data = 32, .tail = { 182, 240, 9, 106, 31, 120, 17, 187, 102, 213, 26, 24, 163, 95, 5, 41, 165, 140 } }; // lhs and rhs should be compatible
const struct compressed_string translation356 = { .data = 43, .tail = { 179, 80, 172, 58, 147, 161, 105, 99, 14, 122, 155, 154, 208, 234, 52, 61, 89, 204, 20, 66, 108, 183, 53, 144 } }; // local variable referenced before assignment
const struct compressed_string translation357 = { .data = 18, .tail = { 185, 91, 86, 123, 157, 70, 190, 168, 151, 69, 216 } }; // malformed f-string
const struct compressed_string translation358 = { .data = 17, .tail = { 185, 78, 226, 173, 114, 69, 6, 238, 206 } }; // math domain error
const struct compressed_string translation359 = { .data = 31, .tail = { 185, 75, 167, 112, 144, 21, 164, 97, 161, 37, 58, 152, 169, 234, 138, 146, 96 } }; // matrix is not positive definite
const struct compressed_string translation360 = { .data = 36, .tail = { 185, 119, 75, 230, 225, 115, 125, 13, 195, 106, 42, 151, 53, 132, 101, 128, 144, 63, 144, 254, 95, 104 } }; // maximum number of dimensions is " "2
const struct compressed_string translation361 = { .data = 32, .tail = { 185, 119, 75, 230, 225, 206, 153, 120, 70, 81, 83, 196, 238, 15, 189, 12, 234, 117 } }; // maximum recursion depth exceeded
const struct compressed_string translation362 = { .data = 19, .tail = { 185, 119, 73, 55, 23, 204, 72, 208, 199, 252, 15, 172 } }; // maxiter must be > 0
const struct compressed_string translation363 = { .data = 21, .tail = { 185, 119, 73, 55, 17, 187, 102, 213, 26, 24, 255, 129, 245, 128 } }; // maxiter should be > 0
const struct compressed_string translation364 = { .data = 34, .tail = { 185, 213, 9, 65, 62, 217, 185, 172, 139, 230, 36, 104, 96, 148, 45, 73, 220, 184 } }; // median argument must be an ndarray
const struct compressed_string translation365 = { .data = 45, .tail = { 185, 221, 159, 128, 86, 179, 80, 165, 25, 70, 164, 150, 58, 250, 65, 90, 205, 66, 148, 93, 135, 44, 141, 56, 147, 128 } }; // memory allocation failed, allocating %u bytes
const struct compressed_string translation366 = { .data = 40, .tail = { 185, 221, 159, 128, 86, 179, 80, 165, 25, 70, 164, 150, 58, 250, 70, 230, 88, 9, 2, 205, 79, 35, 168 } }; // memory allocation failed, heap is locked
const struct compressed_string translation367 = { .data = 27, .tail = { 185, 221, 159, 142, 168, 125, 131, 107, 172, 28, 137, 102, 22, 39, 216, 192 } }; // memoryview offset too large
const struct compressed_string translation368 = { .data = 48, .tail = { 185, 221, 159, 142, 168, 125, 190, 225, 99, 93, 167, 112, 144, 21, 164, 16, 190, 109, 41, 139, 24, 109, 66, 73, 222, 19, 232, 96 } }; // memoryview: length is not a multiple of itemsize
const struct compressed_string translation369 = { .data = 33, .tail = { 187, 84, 197, 243, 18, 52, 49, 70, 190, 44, 114, 126, 144, 206, 28, 235, 154, 29, 64 } }; // mode must be complete, or reduced
const struct compressed_string translation370 = { .data = 40, .tail = { 187, 57, 138, 158, 206, 103, 1, 181, 26, 185, 157, 90, 226, 119, 37, 21, 41, 33, 134, 69, 152 } }; // more degrees of freedom than data points
const struct compressed_string translation371 = { .data = 25, .tail = { 190, 109, 41, 139, 24, 254, 125, 194, 40, 40, 132, 217, 110, 107, 32 } }; // multiple *x in assignment
const struct compressed_string translation372 = { .data = 45, .tail = { 190, 109, 41, 139, 24, 208, 160, 224, 110, 93, 76, 34, 196, 146, 208, 197, 139, 143, 83, 102, 69, 25, 117, 178, 82, 64 } }; // multiple bases have instance lay-out conflict
const struct compressed_string translation373 = { .data = 42, .tail = { 190, 98, 70, 96, 199, 145, 241, 217, 158, 160, 159, 108, 220, 214, 70, 172, 227, 200, 248, 26, 229, 105, 40, 202 } }; // must use keyword argument for key function
const struct compressed_string translation374 = { .data = 23, .tail = { 82, 185, 142, 124, 186, 115, 9, 11, 206, 69, 79, 84, 83, 168 } }; // name '%q' isn't defined
const struct compressed_string translation375 = { .data = 13, .tail = { 82, 185, 137, 102, 22, 101, 216 } }; // name too long
const struct compressed_string translation376 = { .data = 31, .tail = { 82, 148, 234, 98, 141, 83, 8, 163, 198, 248, 224, 101, 99, 56, 195, 60, 157, 64 } }; // native code in .mpy unsupported
const struct compressed_string translation377 = { .data = 24, .tail = { 90, 147, 185, 112, 44, 107, 180, 238, 27, 169, 190, 182, 110, 208 } }; // ndarray length overflows
const struct compressed_string translation378 = { .data = 34, .tail = { 83, 58, 139, 179, 152, 157, 201, 71, 42, 142, 165, 108, 156, 9, 97, 149, 193, 83, 200 } }; // need more than %d values to unpack
const struct compressed_string translation379 = { .data = 20, .tail = { 83, 216, 165, 58, 152, 141, 211, 89, 20, 108, 172, 128 } }; // negative shift count
const struct compressed_string translation380 = { .data = 24, .tail = { 83, 137, 58, 132, 90, 159, 113, 124, 196, 141, 12, 34, 200 } }; // nested index must be int
const struct compressed_string translation381 = { .data = 30, .tail = { 86, 5, 73, 78, 166, 15, 189, 15, 18, 140, 162, 88, 57, 185, 36, 24 } }; // no active exception to reraise
const struct compressed_string translation382 = { .data = 29, .tail = { 86, 26, 34, 213, 23, 97, 171, 56, 86, 91, 53, 10, 195, 86, 202, 212 } }; // no binding for nonlocal found
const struct compressed_string translation383 = { .data = 17, .tail = { 86, 21, 61, 75, 54, 145, 130, 167, 145, 184 } }; // no default packer
const struct compressed_string translation384 = { .data = 15, .tail = { 86, 21, 61, 75, 54, 145, 6, 117 } }; // no default seed
const struct compressed_string translation385 = { .data = 20, .tail = { 86, 23, 106, 230, 198, 20, 174, 117, 28, 249, 116, 230 } }; // no module named '%q'
const struct compressed_string translation386 = { .data = 45, .tail = { 86, 95, 85, 79, 82, 205, 164, 19, 237, 155, 154, 200, 213, 173, 102, 237, 2, 167, 169, 102, 210, 9, 246, 205, 205, 100 } }; // non-default argument follows default argument
const struct compressed_string translation387 = { .data = 13, .tail = { 86, 95, 86, 231, 220, 85, 54, 73 } }; // non-hex digit
const struct compressed_string translation388 = { .data = 14, .tail = { 86, 144, 66, 140, 177, 36, 178 } }; // not a constant
const struct compressed_string translation389 = { .data = 29, .tail = { 86, 145, 25, 198, 25, 228, 234, 53, 103, 8, 184, 204, 137, 227, 7, 0 } }; // not supported for input types
const struct compressed_string translation390 = { .data = 35, .tail = { 92, 223, 67, 112, 218, 140, 50, 44, 192, 190, 98, 70, 134, 10, 69, 140, 162, 71, 218 } }; // number of points must be at least 2
const struct compressed_string translation391 = { .data = 7, .tail = { 109, 62, 103, 73, 0 } }; // object 
const struct compressed_string translation392 = { .data = 33, .tail = { 109, 62, 103, 73, 28, 249, 71, 48, 144, 188, 228, 16, 156, 226, 198, 25, 197, 146, 36 } }; // object '%s' isn't a tuple or list
const struct compressed_string translation393 = { .data = 22, .tail = { 109, 62, 103, 73, 10, 210, 17, 68, 31, 76, 154, 208, 192 } }; // object not in sequence
const struct compressed_string translation394 = { .data = 32, .tail = { 109, 62, 103, 73, 13, 168, 158, 48, 99, 159, 40, 230, 55, 40, 10, 194, 198, 190, 143, 0 } }; // object of type '%s' has no len()
const struct compressed_string translation395 = { .data = 36, .tail = { 109, 62, 103, 73, 29, 146, 119, 26, 103, 93, 77, 198, 29, 165, 168, 214, 14, 125, 50, 142, 117 } }; // object with buffer protocol required
const struct compressed_string translation396 = { .data = 19, .tail = { 109, 117, 131, 144, 144, 37, 152, 88, 159, 99 } }; // offset is too large
const struct compressed_string translation397 = { .data = 61, .tail = { 109, 117, 131, 145, 124, 196, 141, 12, 43, 47, 169, 79, 98, 148, 234, 96, 150, 161, 88, 108, 230, 82, 110, 39, 114, 81, 166, 117, 212, 220, 88, 215, 105, 220 } }; // offset must be non-negative and no greater than buffer length
const struct compressed_string translation398 = { .data = 33, .tail = { 101, 183, 1, 106, 78, 229, 196, 10, 18, 141, 12, 81, 150, 133, 38, 165, 39, 80 } }; // only ndarrays can be concatenated
const struct compressed_string translation399 = { .data = 48, .tail = { 101, 183, 2, 44, 148, 56, 29, 146, 119, 17, 39, 143, 191, 236, 30, 130, 242, 33, 238, 101, 63, 0, 78, 98, 51, 140, 51, 201, 212 } }; // only slices with step=1 (aka None) are supported
const struct compressed_string translation400 = { .data = 6, .tail = { 108, 81, 170, 96 } }; // opcode
const struct compressed_string translation401 = { .data = 40, .tail = { 108, 27, 146, 214, 5, 27, 54, 168, 86, 145, 161, 141, 29, 138, 180, 40, 145, 45, 177, 206, 230, 224 } }; // operands could not be broadcast together
const struct compressed_string translation402 = { .data = 39, .tail = { 108, 27, 148, 163, 40, 72, 21, 61, 81, 78, 163, 86, 113, 246, 254, 64, 157, 203, 136, 12, 182, 224 } }; // operation is defined for 2D arrays only
const struct compressed_string translation403 = { .data = 38, .tail = { 108, 27, 148, 163, 40, 72, 21, 61, 81, 78, 163, 86, 112, 181, 39, 114, 226, 3, 45, 184 } }; // operation is defined for ndarrays only
const struct compressed_string translation404 = { .data = 51, .tail = { 108, 27, 148, 163, 40, 72, 9, 124, 88, 238, 107, 39, 81, 171, 56, 251, 63, 33, 248, 179, 88, 201, 65, 59, 151, 16, 25, 109, 192 } }; // operation is implemented for 1D Boolean arrays only
const struct compressed_string translation405 = { .data = 40, .tail = { 108, 27, 148, 163, 40, 72, 10, 210, 18, 248, 177, 220, 214, 78, 161, 148, 45, 73, 220, 184, 128 } }; // operation is not implemented on ndarrays
const struct compressed_string translation406 = { .data = 41, .tail = { 108, 27, 148, 163, 40, 72, 10, 210, 35, 56, 195, 60, 157, 70, 172, 227, 100, 234, 106, 39, 140, 24 } }; // operation is not supported for given type
const struct compressed_string translation407 = { .data = 43, .tail = { 108, 27, 148, 163, 40, 86, 145, 25, 198, 25, 228, 234, 53, 103, 19, 185, 132, 92, 102, 68, 241, 131, 128 } }; // operation not supported for the input types
const struct compressed_string translation408 = { .data = 57, .tail = { 103, 175, 163, 192, 31, 124, 29, 36, 234, 8, 83, 114, 114, 164, 155, 250, 70, 153, 145, 18, 232, 187, 6, 212, 88, 215, 105, 220, 114, 168, 213, 178, 181 } }; // ord() expected a character, but string of length %d found
const struct compressed_string translation409 = { .data = 22, .tail = { 108, 200, 39, 114, 224, 36, 9, 102, 17, 114, 181, 128 } }; // out array is too small
const struct compressed_string translation410 = { .data = 18, .tail = { 108, 200, 220, 160, 118, 118, 93, 132, 241, 131 } }; // out has wrong type
const struct compressed_string translation411 = { .data = 41, .tail = { 108, 200, 242, 62, 59, 51, 212, 36, 5, 105, 17, 156, 97, 158, 78, 163, 86, 113, 174, 86, 146, 140, 160 } }; // out keyword is not supported for function
const struct compressed_string translation412 = { .data = 31, .tail = { 108, 200, 190, 98, 70, 134, 8, 107, 102, 41, 21, 53, 131, 4, 238, 92, 0 } }; // out must be a float dense array
const struct compressed_string translation413 = { .data = 22, .tail = { 108, 200, 190, 98, 70, 134, 9, 66, 212, 157, 203, 128 } }; // out must be an ndarray
const struct compressed_string translation414 = { .data = 26, .tail = { 108, 200, 190, 98, 70, 134, 27, 81, 173, 152, 164, 86, 120, 193, 128 } }; // out must be of float dtype
const struct compressed_string translation415 = { .data = 27, .tail = { 108, 206, 51, 32, 157, 203, 129, 185, 64, 236, 236, 187, 9, 227, 6 } }; // output array has wrong type
const struct compressed_string translation416 = { .data = 31, .tail = { 108, 206, 51, 32, 157, 203, 129, 124, 196, 141, 12, 81, 150, 83, 108, 182, 96 } }; // output array must be contiguous
const struct compressed_string translation417 = { .data = 44, .tail = { 110, 166, 250, 217, 187, 10, 50, 245, 55, 148, 93, 133, 153, 118, 8, 178, 37, 133, 202, 155, 162, 152, 236, 207, 80 } }; // overflow converting long int to machine word
const struct compressed_string translation418 = { .data = 17, .tail = { 195, 96, 106, 237, 112, 119, 196, 240, 57, 116 } }; // pop from empty %q
const struct compressed_string translation419 = { .data = 23, .tail = { 195, 66, 74, 50, 149, 129, 62, 192, 181, 147, 113, 252, 255, 152 } }; // positional arg after **
const struct compressed_string translation420 = { .data = 32, .tail = { 195, 66, 74, 50, 149, 129, 62, 192, 181, 147, 113, 228, 124, 118, 103, 168, 39, 216 } }; // positional arg after keyword arg
const struct compressed_string translation421 = { .data = 30, .tail = { 195, 118, 244, 120, 15, 232, 245, 4, 251, 102, 230, 178, 40, 74, 173, 35, 67, 31, 88 } }; // pow() 3rd argument cannot be 0
const struct compressed_string translation422 = { .data = 40, .tail = { 195, 118, 244, 120, 14, 201, 59, 143, 232, 9, 246, 205, 205, 102, 3, 159, 76, 163, 156, 4, 89, 61, 141, 224 } }; // pow() with 3 arguments requires integers
const struct compressed_string translation423 = { .data = 40, .tail = { 198, 109, 97, 114, 143, 40, 20, 101, 214, 201, 73, 29, 146, 119, 21, 71, 58, 74, 50, 139, 148, 121, 64 } }; // pull masks conflict with direction masks
const struct compressed_string translation424 = { .data = 48, .tail = { 115, 43, 2, 90, 132, 185, 108, 138, 79, 192, 193, 60, 192, 190, 98, 70, 134, 27, 80, 125, 50, 86, 22, 53, 218, 119 } }; // real and imaginary parts must be of equal length
const struct compressed_string translation425 = { .data = 44, .tail = { 115, 233, 147, 137, 58, 139, 26, 237, 59, 142, 85, 26, 102, 67, 105, 243, 58, 72, 220, 160, 88, 215, 105, 220, 114, 168 } }; // requested length %d but object has length %d
const struct compressed_string translation426 = { .data = 40, .tail = { 115, 140, 218, 96, 80, 149, 90, 70, 134, 40, 81, 34, 88, 70, 14, 137, 170, 29, 68, 241, 131 } }; // results cannot be cast to specified type
const struct compressed_string translation427 = { .data = 32, .tail = { 118, 181, 129, 62, 217, 185, 172, 139, 230, 36, 104, 96, 148, 45, 73, 220, 184 } }; // roll argument must be an ndarray
const struct compressed_string translation428 = { .data = 14, .tail = { 120, 197, 146, 125, 30, 230, 83, 244, 175, 128 } }; // rsplit(None,n)
const struct compressed_string translation429 = { .data = 54, .tail = { 141, 203, 6, 47, 152, 145, 161, 143, 115, 41, 250, 65, 45, 66, 44, 158, 198, 225, 156, 16, 156, 226, 198, 27, 80, 139, 39, 177, 188, 0 } }; // shape must be None, and integer or a tuple of integers
const struct compressed_string translation430 = { .data = 42, .tail = { 141, 203, 6, 47, 152, 145, 161, 132, 89, 61, 141, 195, 56, 156, 226, 198, 27, 80, 139, 39, 177, 188, 0 } }; // shape must be integer or tuple of integers
const struct compressed_string translation431 = { .data = 10, .tail = { 141, 217, 228, 57, 149, 64 } }; // short read
const struct compressed_string translation432 = { .data = 43, .tail = { 132, 217, 66, 180, 130, 181, 155, 177, 212, 34, 136, 151, 69, 216, 106, 207, 114, 145, 24, 58, 38, 168, 110 } }; // sign not allowed in string format specifier
const struct compressed_string translation433 = { .data = 50, .tail = { 132, 217, 66, 180, 130, 181, 155, 177, 212, 118, 73, 220, 34, 201, 236, 110, 53, 103, 185, 72, 140, 29, 19, 84, 55, 28, 233, 204 } }; // sign not allowed with integer format specifier 'c'
const struct compressed_string translation434 = { .data = 33, .tail = { 132, 250, 24, 72, 21, 61, 81, 78, 163, 86, 112, 181, 39, 114, 226, 3, 45, 184 } }; // size is defined for ndarrays only
const struct compressed_string translation435 = { .data = 44, .tail = { 132, 250, 24, 190, 98, 69, 202, 105, 184, 108, 207, 140, 110, 88, 49, 219, 115, 81, 152, 58, 137, 109, 142, 119, 55 } }; // size must match out.shape when used together
const struct compressed_string translation436 = { .data = 18, .tail = { 139, 149, 172, 17, 100, 55, 83, 125, 108, 221, 128 } }; // small int overflow
const struct compressed_string translation437 = { .data = 13, .tail = { 134, 214, 67, 158, 140, 211, 231, 243, 0 } }; // soft reboot\n
const struct compressed_string translation438 = { .data = 32, .tail = { 134, 121, 4, 251, 102, 230, 178, 47, 152, 145, 161, 130, 80, 181, 39, 114, 224 } }; // sort argument must be an ndarray
const struct compressed_string translation439 = { .data = 41, .tail = { 134, 128, 78, 229, 192, 190, 98, 70, 134, 27, 81, 27, 150, 12, 122, 23, 229, 7, 73, 70, 95, 72, 255, 95, 0 } }; // sos array must be of shape (n_section, 6)
const struct compressed_string translation440 = { .data = 28, .tail = { 134, 143, 223, 238, 244, 143, 233, 252, 8, 221, 179, 106, 141, 12, 21, 172, 25, 78, 0 } }; // sos[:, 3] should be all ones
const struct compressed_string translation441 = { .data = 35, .tail = { 134, 141, 82, 210, 28, 250, 101, 28, 224, 36, 155, 150, 150, 48, 79, 182, 110, 107, 48 } }; // sosfilt requires iterable arguments
const struct compressed_string translation442 = { .data = 27, .tail = { 140, 89, 38, 81, 118, 29, 146, 119, 17, 157, 61, 84, 44, 78, 92, 224 } }; // splitting with sub-captures
const struct compressed_string translation443 = { .data = 29, .tail = { 137, 108, 5, 105, 14, 101, 77, 203, 75, 24, 213, 218, 226, 36, 158, 64 } }; // stop not reachable from start
const struct compressed_string translation444 = { .data = 30, .tail = { 137, 115, 43, 134, 193, 185, 74, 50, 133, 105, 17, 156, 97, 158, 78, 160 } }; // stream operation not supported
const struct compressed_string translation445 = { .data = 35, .tail = { 137, 116, 93, 129, 62, 217, 185, 172, 142, 201, 59, 182, 100, 18, 131, 90, 53, 81, 118 } }; // string argument without an encoding
const struct compressed_string translation446 = { .data = 25, .tail = { 137, 116, 93, 130, 45, 79, 184, 108, 200, 109, 67, 146, 236, 96 } }; // string index out of range
const struct compressed_string translation447 = { .data = 39, .tail = { 137, 116, 93, 130, 45, 82, 135, 2, 249, 137, 26, 24, 69, 147, 216, 222, 61, 33, 90, 71, 40 } }; // string indices must be integers, not %s
const struct compressed_string translation448 = { .data = 19, .tail = { 140, 233, 18, 232, 187, 5, 105, 26, 182, 86, 160 } }; // substring not found
const struct compressed_string translation449 = { .data = 23, .tail = { 140, 224, 223, 209, 224, 40, 75, 206, 70, 168, 181, 16, 118, 212 } }; // super() can't find self
const struct compressed_string translation450 = { .data = 20, .tail = { 142, 22, 75, 184, 55, 118, 112, 138, 63, 254, 248, 126, 158, 224 } }; // syntax error in JSON
const struct compressed_string translation451 = { .data = 24, .tail = { 148, 185, 182, 100, 118, 36, 148, 93, 134, 172, 227, 91, 103, 184 } }; // timeout waiting for flux
const struct compressed_string translation452 = { .data = 31, .tail = { 148, 185, 182, 100, 118, 36, 148, 93, 134, 172, 225, 22, 167, 220, 99, 54, 131 } }; // timeout waiting for index pulse
const struct compressed_string translation453 = { .data = 42, .tail = { 148, 185, 196, 149, 240, 27, 50, 27, 80, 228, 187, 24, 213, 156, 98, 197, 58, 179, 220, 74, 92, 254, 82 } }; // timestamp out of range for platform time_t
const struct compressed_string translation454 = { .data = 44, .tail = { 150, 211, 137, 56, 20, 37, 26, 24, 69, 234, 222, 71, 81, 171, 56, 169, 172, 24, 39, 114, 226, 3, 45, 184 } }; // tobytes can be invoked for dense arrays only
const struct compressed_string translation455 = { .data = 13, .tail = { 150, 97, 114, 94, 1, 62, 208 } }; // too many args
const struct compressed_string translation456 = { .data = 19, .tail = { 150, 97, 114, 94, 5, 82, 230, 176, 140, 176 } }; // too many dimensions
const struct compressed_string translation457 = { .data = 16, .tail = { 150, 97, 114, 94, 2, 45, 82, 135, 0 } }; // too many indices
const struct compressed_string translation458 = { .data = 39, .tail = { 150, 97, 114, 94, 7, 82, 182, 78, 4, 176, 202, 224, 169, 228, 61, 7, 223, 7, 73, 58, 142, 85, 240 } }; // too many values to unpack (expected %d)
const struct compressed_string translation459 = { .data = 46, .tail = { 151, 44, 125, 2, 64, 169, 234, 138, 117, 26, 179, 143, 179, 242, 4, 238, 92, 64, 109, 65, 244, 201, 88, 88, 215, 105, 220 } }; // trapz is defined for 1D arrays of equal length
const struct compressed_string translation460 = { .data = 33, .tail = { 151, 44, 125, 2, 64, 169, 234, 138, 117, 26, 179, 143, 179, 242, 9, 38, 229, 165, 142, 0 } }; // trapz is defined for 1D iterables
const struct compressed_string translation461 = { .data = 29, .tail = { 158, 224, 150, 161, 251, 138, 18, 171, 72, 209, 167, 113, 161, 143, 115, 41, 128 } }; // tx and rx cannot both be None
const struct compressed_string translation462 = { .data = 39, .tail = { 158, 48, 99, 159, 46, 156, 194, 66, 243, 144, 74, 10, 148, 60, 73, 105, 99, 26, 20, 24, 158, 48, 96 } }; // type '%q' isn't an acceptable base type
const struct compressed_string translation463 = { .data = 38, .tail = { 158, 48, 97, 180, 249, 157, 36, 115, 229, 211, 152, 220, 160, 43, 2, 153, 116, 211, 50, 99, 159, 46, 156, 192 } }; // type object '%q' has no attribute '%q'
const struct compressed_string translation464 = { .data = 27, .tail = { 158, 48, 98, 75, 200, 224, 125, 129, 156, 127, 64, 79, 182, 110, 107, 48 } }; // type takes 1 or 3 arguments
const struct compressed_string translation465 = { .data = 17, .tail = { 202, 159, 124, 29, 36, 234, 17, 106, 107, 32 } }; // unexpected indent
const struct compressed_string translation466 = { .data = 32, .tail = { 202, 159, 124, 29, 36, 234, 60, 143, 142, 204, 245, 4, 251, 102, 230, 178, 57, 242, 233, 204 } }; // unexpected keyword argument '%q'
const struct compressed_string translation467 = { .data = 20, .tail = { 202, 165, 26, 166, 20, 174, 96, 226, 133, 131, 128 } }; // unicode name escapes
const struct compressed_string translation468 = { .data = 45, .tail = { 202, 162, 212, 214, 69, 88, 225, 121, 200, 185, 77, 55, 4, 188, 6, 204, 155, 132, 90, 154, 200, 177, 245, 59, 0 } }; // unindent doesn't match any outer indent level
const struct compressed_string translation469 = { .data = 48, .tail = { 202, 249, 43, 118, 81, 171, 61, 202, 69, 26, 166, 57, 242, 167, 49, 171, 56, 109, 62, 103, 73, 13, 168, 158, 48, 99, 159, 46, 156, 192 } }; // unknown format code '%c' for object of type '%q'
const struct compressed_string translation470 = { .data = 24, .tail = { 202, 220, 166, 155, 157, 71, 62, 84, 230, 17, 70, 172, 247, 41 } }; // unmatched '%c' in format
const struct compressed_string translation471 = { .data = 20, .tail = { 202, 185, 149, 75, 75, 24, 41, 151, 77, 51, 38 } }; // unreadable attribute
const struct compressed_string translation472 = { .data = 52, .tail = { 202, 198, 113, 134, 121, 58, 141, 89, 238, 82, 41, 185, 57, 82, 77, 199, 62, 84, 230, 61, 31, 95, 126, 93, 252, 1, 72, 69, 169, 247, 28, 170 } }; // unsupported format character '%c' (0x%x) at index %d
const struct compressed_string translation473 = { .data = 29, .tail = { 202, 198, 113, 134, 121, 58, 137, 227, 6, 53, 103, 28, 186, 125, 195, 159, 40, 230 } }; // unsupported type for %q: '%s'
const struct compressed_string translation474 = { .data = 36, .tail = { 202, 198, 113, 134, 121, 58, 137, 227, 7, 3, 86, 113, 203, 167, 220, 57, 242, 233, 207, 210, 57, 242, 233, 204 } }; // unsupported types for %q: '%q', '%q'
const struct compressed_string translation475 = { .data = 19, .tail = { 204, 29, 26, 208, 18, 4, 179, 13, 211, 109, 192 } }; // usecols is too high
const struct compressed_string translation476 = { .data = 28, .tail = { 234, 86, 201, 139, 230, 36, 106, 146, 17, 71, 42, 141, 56, 147, 244, 71, 128 } }; // value must fit in %d byte(s)
const struct compressed_string translation477 = { .data = 16, .tail = { 236, 236, 187, 2, 238, 144, 17, 106, 125, 192 } }; // wrong axis index
const struct compressed_string translation478 = { .data = 20, .tail = { 236, 236, 187, 2, 238, 144, 35, 7, 68, 213, 14, 160 } }; // wrong axis specified
const struct compressed_string translation479 = { .data = 11, .tail = { 236, 236, 187, 10, 207, 24, 48 } }; // wrong dtype
const struct compressed_string translation480 = { .data = 16, .tail = { 236, 236, 187, 4, 90, 159, 113, 60, 96, 192 } }; // wrong index type
const struct compressed_string translation481 = { .data = 16, .tail = { 236, 236, 187, 4, 92, 102, 68, 241, 131 } }; // wrong input type
const struct compressed_string translation482 = { .data = 31, .tail = { 236, 236, 187, 11, 26, 237, 59, 134, 212, 81, 150, 169, 40, 202, 9, 220, 184 } }; // wrong length of condition array
const struct compressed_string translation483 = { .data = 27, .tail = { 236, 236, 187, 11, 26, 237, 59, 134, 212, 34, 212, 251, 130, 119, 46, 0 } }; // wrong length of index array
const struct compressed_string translation484 = { .data = 25, .tail = { 236, 236, 187, 5, 205, 244, 55, 13, 168, 39, 219, 55, 53, 152 } }; // wrong number of arguments
const struct compressed_string translation485 = { .data = 17, .tail = { 236, 236, 187, 6, 204, 227, 50, 39, 140, 24 } }; // wrong output type
const struct compressed_string translation486 = { .data = 21, .tail = { 250, 32, 190, 98, 70, 134, 9, 66, 212, 157, 203, 128 } }; // zi must be an ndarray
const struct compressed_string translation487 = { .data = 24, .tail = { 250, 32, 190, 98, 70, 134, 27, 81, 173, 152, 164, 79, 24, 48 } }; // zi must be of float type
const struct compressed_string translation488 = { .data = 34, .tail = { 250, 32, 190, 98, 70, 134, 27, 81, 27, 150, 12, 122, 23, 229, 7, 73, 70, 95, 72, 251, 124, 0 } }; // zi must be of shape (n_section, 2)

// 15047 bytes worth of translations
// 9424 bytes worth of translations compressed
// 5623 bytes saved
