USB_VID = 0x2E8A
USB_PID = 0x1250
USB_PRODUCT = "STOCKERIO"
USB_MANUFACTURER = "XFAB"

CHIP_VARIANT = RP2350
CHIP_PACKAGE = B
CHIP_FAMILY = rp2

EXTERNAL_FLASH_DEVICES = W25Q16JVxQ
FLASH_SIZE = 0x200000

CIRCUITPY_INTERNAL_NVM_SIZE = 0x1000


CIRCUITPY_ASYNCIO = 1
CIRCUITPY_PWMIO = 1
CIRCUITPY_DIGITALIO = 1
CIRCUITPY_STORAGE = 1
CIRCUITPY_USB_CDC = 1
CIRCUITPY_USB_MSC = 1
CIRCUITPY_USB_HID = 0
CIRCUITPY_USB_MIDI = 0

CIRCUITPY_ALARM = 0
CIRCUITPY_BITMAPTOOLS = 0
CIRCUITPY_BLEIO = 0
CIRCUITPY_BLEIO_HCI = 0
CIRCUITPY_BUSBUS = 0
CIRCUITPY_FONTIO = 0
CIRCUITPY_KEYPAD = 0
CIRCUITPY_NEOPIXEL_WRITE = 0
CIRCUITPY_PARALLELDISPLAYBUS = 0
CIRCUITPY_ROTARYIO = 0
CIRCUITPY_RTC = 0
CIRCUITPY_SDCARDIO = 0
CIRCUITPY_SDIOIO = 0
CIRCUITPY_TERMINALIO = 0
CIRCUITPY_VECTORIO = 0

CIRCUITPY_PICODVI = 0
CIRCUITPY_DISPLAYIO = 0
CIRCUITPY_FRAMEBUFFERIO = 0

CIRCUITPY_SYNTHIO = 0
CIRCUITPY_AUDIOCORE = 0
CIRCUITPY_AUDIOIO = 0
CIRCUITPY_AUDIOBUSIO = 0
CIRCUITPY_AUDIOPWMIO = 0
CIRCUITPY_AUDIOMIXER = 0
CIRCUITPY_AUDIOMP3 = 0
CIRCUITPY_AUDIOFREEVERB = 0
CIRCUITPY_AUDIODELAYS = 0
CIRCUITPY_AUDIOFILTERS = 0

CIRCUITPY_ANALOGIO = 0
CIRCUITPY_PS2IO = 0
CIRCUITPY_RGBMATRIX = 0
CIRCUITPY_BUSIO = 1

CIRCUITPY_SSL = 0
CIRCUITPY_SOCKETPOOL = 0
CIRCUITPY_WIFI = 0

FROZEN_MPY_DIRS =
